repos:
- repo: local
  hooks:
  - id: nbdev_clean
    name: nbdev_clean
    entry: .pixi/envs/default/bin/nbdev_clean
    language: system
    pass_filenames: false
  - id: nbdev_export
    name: nbdev_export
    entry: .pixi/envs/default/bin/nbdev_export
    language: system
    pass_filenames: false
