"""Injecting pure Mojo kernels into the MAX Graph."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_custom_ops.ipynb.

# %% auto 0
__all__ = ['KERNELS_PATH', 'WARP_SIZE', 'MAX_GROUPS', 'AUTO_GPU_THRESHOLD', 'GPU_JOIN_THRESHOLD', 'clear_cache', 'CustomOpsCompiler']

# %% ../nbs/04_custom_ops.ipynb 2
from typing import Any, Dict, List, Union
import pyarrow as pa
import pyarrow.compute as pc
import numpy as np
import time as _time
from pathlib import Path
from max import engine, driver
from max.graph import Graph, TensorType, ops
from max.graph.type import DType, DeviceRef
from .lazy_expr import Expr
from .lazy_frame import LogicalPlan, Scan, Filter, Project, Aggregate, Sort, Limit, Distinct, Join
from .compiler import GraphCompiler, _max_dtype, _CMP_OPS, _PC_CMP_OPS


# %% ../nbs/04_custom_ops.ipynb 4
KERNELS_PATH = (
    str(Path(__file__).parent / "kernels_v261")
    if "__file__" in dir()
    else str(Path("/home/ablearn/mxdf/mxframe/kernels_v261"))
)

WARP_SIZE = 32
# Must match comptime MAX_GROUPS in the Mojo kernels (group_sum/min/max/count/mean.mojo).
# Kernels use shared-memory privatization up to this limit, then fall back to
# global-atomic scatter for larger cardinalities — so no hard ceiling on group count.
MAX_GROUPS = 8192
AUTO_GPU_THRESHOLD = 10_000   # rows; used by device='auto' to pick GPU vs CPU
GPU_JOIN_THRESHOLD = 200_000  # result rows; threshold to use GPU gather after join

# ── Module-level caches ──────────────────────────────────────────────────────
# Persist across CustomOpsCompiler instances so repeated .compute() calls
# reuse the compiled MAX Graph model instead of recompiling from scratch.
_SESSION_CACHE: Dict[str, Any] = {}       # device_name → InferenceSession
_MODEL_CACHE: Dict[tuple, tuple] = {}     # cache_key → (model, agg_names)
_GROUP_ENCODE_CACHE: Dict[tuple, tuple] = {}  # (table_id, num_rows, keys) → encoding result
_INPUT_PREP_CACHE: Dict[tuple, dict] = {}    # (table_id, num_rows, plan_sig, device) → prepared arrays
_POST_OP_MODEL_CACHE: Dict[tuple, Any] = {}  # ("sort_indices"|"unique_mask", N, device) → model  (GPU only)
_GPU_BUFFER_CACHE: Dict[tuple, Dict[str, Any]] = {}  # prep_key → {col_name: driver.Buffer} (stable inputs only, never __filter_mask__)
_JOIN_RESULT_CACHE: Dict[tuple, Any] = {}  # (left_stable_key, right_stable_key, left_on, right_on) → pa.Table


def _get_or_create_session(device_name: str, driver_device) -> Any:
    """Return a cached InferenceSession, creating one if needed."""
    if device_name not in _SESSION_CACHE:
        _SESSION_CACHE[device_name] = engine.InferenceSession(devices=[driver_device])
    return _SESSION_CACHE[device_name]


def clear_cache():
    """Clear the compiled model cache and session cache.

    Call this after modifying Mojo kernel source files, or to force
    recompilation on the next .compute() call.
    """
    _MODEL_CACHE.clear()
    _SESSION_CACHE.clear()
    _GROUP_ENCODE_CACHE.clear()
    _INPUT_PREP_CACHE.clear()
    _POST_OP_MODEL_CACHE.clear()
    _GPU_BUFFER_CACHE.clear()
    _JOIN_RESULT_CACHE.clear()


class CustomOpsCompiler(GraphCompiler):
    """Compiles a LogicalPlan into a MAX Graph with custom Mojo kernels.

    Extends GraphCompiler with:
    1. Pre-filter   -- inherited _strip_filters applies Filter nodes in PyArrow.
    2. Group ids    -- PyArrow dictionary-encodes group-by keys into int32 ids.
    3. Kernel dispatch -- grouped sum/min/max/mean/count routed to Mojo kernels.
    4. Keys in result -- group-by key columns are prepended to the output table.
    5. GPU path     -- kernels run on GPU when device='gpu' or device='auto' (N > 100K).
    6. Graph caching -- compiled models are cached by plan signature + input schema.
    7. Post-ops     -- Sort/Limit/Distinct applied via Mojo kernels after graph execution.
    """

    def __init__(self, kernels_path: str = None, device: str = "cpu"):
        super().__init__(device=device)
        self.kernels_path = kernels_path or KERNELS_PATH
        self.last_compile_provenance = {}
        # Reuse module-level cached session to avoid InferenceSession overhead
        self.session = _get_or_create_session(self._session_device, self._driver_device)

    def _maybe_switch_device(self, N: int) -> None:
        """For device='auto': re-evaluate CPU vs GPU based on row count.

        Switches and re-creates the InferenceSession only when the decision changes.
        Threshold: N > AUTO_GPU_THRESHOLD and GPU available -> GPU, otherwise CPU.
        """
        if self._device_arg != "auto":
            return
        want_gpu = self._has_gpu and N > AUTO_GPU_THRESHOLD
        have_gpu = (self._session_device == "gpu")
        if want_gpu == have_gpu:
            return
        if want_gpu:
            self._device_ref = DeviceRef.GPU(0)
            self.session = _get_or_create_session("gpu", self._gpu_driver)
            self._session_device = "gpu"
        else:
            self._device_ref = DeviceRef.CPU()
            self.session = _get_or_create_session("cpu", driver.CPU())
            self._session_device = "cpu"

    @staticmethod
    def _normalize_numeric_dtype(arr: np.ndarray) -> Union[np.ndarray, None]:
        """Normalize numeric arrays to MAX-friendly dtypes."""
        kind = arr.dtype.kind
        if kind in ("i", "u"):
            if arr.dtype not in (np.dtype("int32"), np.dtype("int64")):
                return arr.astype(np.int64, copy=False)
            return arr
        if kind == "f":
            if arr.dtype not in (np.dtype("float32"), np.dtype("float64")):
                return arr.astype(np.float64, copy=False)
            return arr
        if kind == "b":
            return arr.astype(np.bool_, copy=False)
        return None

    @staticmethod
    def _arrow_array_to_numpy_view(arr: pa.Array) -> Union[np.ndarray, None]:
        """Try zero-copy NumPy view from Arrow primitive array buffers."""
        if arr.null_count != 0:
            return None
        typ = arr.type
        if pa.types.is_int32(typ):
            dtype = np.int32
            itemsize = 4
        elif pa.types.is_int64(typ):
            dtype = np.int64
            itemsize = 8
        elif pa.types.is_uint32(typ):
            dtype = np.uint32
            itemsize = 4
        elif pa.types.is_uint64(typ):
            dtype = np.uint64
            itemsize = 8
        elif pa.types.is_float32(typ):
            dtype = np.float32
            itemsize = 4
        elif pa.types.is_float64(typ):
            dtype = np.float64
            itemsize = 8
        else:
            return None

        buffers = arr.buffers()
        if len(buffers) < 2 or buffers[1] is None:
            return None

        offset_bytes = arr.offset * itemsize
        try:
            return np.frombuffer(buffers[1], dtype=dtype, count=len(arr), offset=offset_bytes)
        except Exception:
            return None

    @staticmethod
    def _is_numeric_arrow_type(typ) -> bool:
        """Return True for Arrow types we can convert to numpy tensors."""
        return (pa.types.is_integer(typ) or pa.types.is_floating(typ)
                or pa.types.is_boolean(typ))

    def _column_to_numpy_cached(self, col: Union[pa.Array, pa.ChunkedArray]) -> tuple[Union[np.ndarray, None], bool, bool]:
        """Convert Arrow column to numeric NumPy with zero-copy-first strategy."""
        if isinstance(col, pa.ChunkedArray):
            if len(col.chunks) == 1:
                arr = col.chunks[0]
            else:
                arr = col.combine_chunks()
        else:
            arr = col

        view = self._arrow_array_to_numpy_view(arr)
        if view is not None:
            norm = self._normalize_numeric_dtype(view)
            if norm is not None:
                out = norm if norm.flags['C_CONTIGUOUS'] else np.ascontiguousarray(norm)
                return out, False, True

        try:
            np_arr = arr.to_numpy(zero_copy_only=True)
            norm = self._normalize_numeric_dtype(np_arr)
            if norm is not None:
                out = norm if norm.flags['C_CONTIGUOUS'] else np.ascontiguousarray(norm)
                return out, False, False
        except Exception:
            pass

        try:
            np_arr = arr.to_numpy(zero_copy_only=False)
            norm = self._normalize_numeric_dtype(np_arr)
            if norm is not None:
                out = norm if norm.flags['C_CONTIGUOUS'] else np.ascontiguousarray(norm)
                return out, True, False
        except Exception:
            return None, False, False
        return None, False, False

    def _to_gpu_input(self, arr: np.ndarray) -> tuple[Any, str]:
        """Build GPU input buffer using fastest available safe path."""
        try:
            return driver.Buffer.from_numpy(arr).to(self._gpu_driver), "from_numpy"
        except Exception:
            contiguous = np.ascontiguousarray(arr)
            return driver.Buffer.from_numpy(contiguous).to(self._gpu_driver), "from_numpy_contiguous"

    @classmethod
    def _can_compile_predicate_gpu(cls, expr: Expr) -> bool:
        """Return True if this predicate can be compiled to a MAX Graph int32 mask node.

        Supports numeric col references, numeric literals, and gt/ge/lt/le/eq/and/or
        combinations. String columns, nulls, and non-comparison ops are not supported.
        """
        op = expr.op
        if op == "col":
            return True
        if op == "lit":
            return isinstance(expr.args[0], (int, float, bool))
        if op in ("gt", "ge", "lt", "le", "eq", "ne", "and", "or"):
            return all(cls._can_compile_predicate_gpu(a) for a in expr.args)
        # isin, startswith, case_when, not -> need PyArrow eval -> CPU path only
        return False

    def _visit_predicate_to_mask(self, expr: Expr, nodes) -> Any:
        """Compile a filter predicate Expr into an int32 mask graph node (0=skip, 1=keep).

        Called inside a MAX Graph context. The returned node has dtype int32 and
        the same shape as the input column tensors.
        """
        op = expr.op
        if op in ("gt", "ge", "lt", "le", "eq"):
            lhs = self._visit_expr(expr.args[0], nodes)
            rhs = self._visit_expr(expr.args[1], nodes)
            return ops.cast(_CMP_OPS[op](lhs, rhs), DType.int32)
        if op == "ne":
            lhs = self._visit_expr(expr.args[0], nodes)
            rhs = self._visit_expr(expr.args[1], nodes)
            eq_node = ops.cast(ops.equal(lhs, rhs), DType.int32)
            one = ops.constant(np.array([1], dtype=np.int32), dtype=DType.int32, device=self._device_ref)
            return ops.sub(one, eq_node)
        if op == "and":
            l = self._visit_predicate_to_mask(expr.args[0], nodes)
            r = self._visit_predicate_to_mask(expr.args[1], nodes)
            return ops.mul(l, r)
        if op == "or":
            l = self._visit_predicate_to_mask(expr.args[0], nodes)
            r = self._visit_predicate_to_mask(expr.args[1], nodes)
            zero = ops.constant(0, dtype=DType.int32, device=self._device_ref)
            return ops.cast(ops.greater(ops.add(l, r), zero), DType.int32)
        if op == "col":
            return ops.cast(nodes[expr.args[0]], DType.int32)
        if op == "lit":
            val = expr.args[0]
            if isinstance(val, int):
                return ops.constant(val, dtype=DType.int64, device=self._device_ref)
            return ops.constant(float(val), dtype=DType.float32, device=self._device_ref)
        raise ValueError(f"Cannot compile predicate op '{op}' to GPU mask.")


    # -- Derived-column pre-computation (case_when / isin / startswith) ----

    @staticmethod
    def _needs_precompute(expr) -> bool:
        """True if expr contains case_when, isin, or startswith anywhere."""
        if expr.op in ("case_when", "isin", "startswith", "contains", "not", "year"):
            return True
        from .lazy_expr import Expr as _Expr
        return any(isinstance(a, _Expr) and CustomOpsCompiler._needs_precompute(a)
                   for a in expr.args)

    def _eval_expr_arrow(self, expr, table):
        """Evaluate expr on an Arrow table, returning a pa.Array."""
        from .lazy_expr import Expr as _Expr
        op, args = expr.op, expr.args
        if op == "col":
            col_arr = table.column(args[0])
            return col_arr.combine_chunks() if isinstance(col_arr, pa.ChunkedArray) else col_arr
        if op == "lit":
            val = args[0]
            n = len(table)
            if isinstance(val, (int, float)):
                return pa.array(np.full(n, val, dtype=np.float32))
            return pa.array([val] * n)
        if op in ("add", "sub", "mul", "div"):
            lhs = self._eval_expr_arrow(args[0], table)
            rhs = self._eval_expr_arrow(args[1], table)
            fn = {"add": pc.add, "sub": pc.subtract, "mul": pc.multiply, "div": pc.divide}[op]
            return fn(lhs, rhs)
        if op in _PC_CMP_OPS:
            lhs = self._eval_expr_arrow(args[0], table)
            rhs = self._eval_expr_arrow(args[1], table)
            return _PC_CMP_OPS[op](lhs, rhs)
        if op == "not":
            return pc.invert(self._eval_expr_arrow(args[0], table))
        if op == "isin":
            col_arr = self._eval_expr_arrow(args[0], table)
            return pc.is_in(col_arr, value_set=pa.array(args[1]))
        if op == "startswith":
            col_arr = self._eval_expr_arrow(args[0], table)
            return pc.starts_with(col_arr, pattern=args[1])
        if op == "contains":
            col_arr = self._eval_expr_arrow(args[0], table)
            return pc.match_substring(col_arr, pattern=args[1])
        if op == "case_when":
            cond  = self._eval_expr_arrow(args[0], table)
            then  = self._eval_expr_arrow(args[1], table)
            else_ = self._eval_expr_arrow(args[2], table)
            result = pc.if_else(cond, then, else_)
            return result.cast(pa.float32()) if result.type != pa.float32() else result
        raise NotImplementedError(f"_eval_expr_arrow: unsupported op '{op}'")

    def _extract_derived_cols(self, plan):
        """Rewrite case_when/isin/startswith in agg/project exprs as derived col refs.

        Returns (rewritten_plan, derived_specs) where derived_specs is a list of
        (col_name, original_expr) pairs to be evaluated in PyArrow before the graph.
        """
        from .lazy_expr import Expr as _Expr
        derived_specs = []

        def _rewrite_expr(expr):
            if not CustomOpsCompiler._needs_precompute(expr):
                return expr
            if expr.op in ("case_when", "isin", "startswith", "contains"):
                name = f"__cw_{len(derived_specs)}__"
                derived_specs.append((name, expr))
                new_expr = _Expr("col", name)
                new_expr._alias = expr._alias
                return new_expr
            new_args = [
                _rewrite_expr(a) if isinstance(a, _Expr) else a
                for a in expr.args
            ]
            new_expr = _Expr(expr.op, *new_args)
            new_expr._alias = expr._alias
            return new_expr

        def _rewrite_plan(p):
            if isinstance(p, Scan): return p
            if isinstance(p, Aggregate):
                new_aggs = [_rewrite_expr(e) for e in p.aggs]
                return Aggregate(_rewrite_plan(p.input), p.group_by, new_aggs)
            if isinstance(p, Project):
                new_exprs = [_rewrite_expr(e) for e in p.exprs]
                return Project(_rewrite_plan(p.input), new_exprs)
            if isinstance(p, Filter):
                return Filter(_rewrite_plan(p.input), p.predicate)
            if isinstance(p, (Sort, Limit, Distinct)):
                import copy
                new_node = copy.copy(p)
                new_node.input = _rewrite_plan(p.input)
                return new_node
            if isinstance(p, Join):
                return Join(_rewrite_plan(p.left), _rewrite_plan(p.right),
                            p.left_on, p.right_on, p.how)
            if hasattr(p, "input"):
                p.input = _rewrite_plan(p.input)
            return p

        new_plan = _rewrite_plan(plan)
        return new_plan, derived_specs


    def _compute_global_agg_pyarrow(self, table: "pa.Table", agg_node) -> "pa.Table":
        """Evaluate a global (ungrouped) aggregate using PyArrow/numpy.

        Called when the plan has an Aggregate with no group_by keys.  Covers
        sum / min / max / mean / count with arbitrary expression trees (mul, add,
        case_when, startswith, isin, …) via ``_eval_expr_arrow``.

        Returns a single-row pa.Table with one column per aggregation.
        """
        import pyarrow as _pa
        result_cols = {}
        for i, expr in enumerate(agg_node.aggs):
            name = expr._alias or f"agg_{i}"
            op   = expr.op
            if op in ("sum", "min", "max", "mean"):
                inner_arr = self._eval_expr_arrow(expr.args[0], table)
                arr_np    = inner_arr.to_numpy(zero_copy_only=False).astype("float64")
                if   op == "sum":  val = float(arr_np.sum())
                elif op == "min":  val = float(arr_np.min())
                elif op == "max":  val = float(arr_np.max())
                else:              val = float(arr_np.mean())   # mean
                result_cols[name] = _pa.array([val], type=_pa.float64())
            elif op == "count":
                result_cols[name] = _pa.array([len(table)], type=_pa.int64())
            else:
                raise NotImplementedError(
                    f"_compute_global_agg_pyarrow: unsupported agg op '{op}'"
                )
        return _pa.table(result_cols)

    def _compute_cache_key(self, plan, all_names, all_arrays, n_groups, optimizer_trace=None):
        """Compute a hashable cache key for the compiled graph model.

        Key components:
        - plan_sig: structural signature of the logical plan (ops, column refs, literals)
        - input_sig: (name, dtype, shape) per input tensor -- determines graph input types
        - n_groups: number of groups (affects output shapes in grouped path)
        - device: CPU vs GPU (different kernel dispatch + output shapes)
        """
        plan_sig = plan.signature()
        input_sig = tuple(
            (n, str(all_arrays[n].dtype), all_arrays[n].shape[0]) for n in all_names
        )
        optimizer_sig = tuple(optimizer_trace or ())
        return (plan_sig, input_sig, n_groups, self._session_device, optimizer_sig)

    @classmethod
    def _collect_predicates(cls, plan):
        """Collect all Filter predicates from the plan tree."""
        preds = []
        def _walk(p):
            if isinstance(p, Filter):
                preds.append(p.predicate)
                _walk(p.input)
            elif isinstance(p, Join):
                raise RuntimeError("_collect_predicates: Join should have been materialized")
            elif isinstance(p, (Sort, Limit, Distinct)):
                _walk(p.input)
            elif hasattr(p, 'input'):
                _walk(p.input)
        _walk(plan)
        return preds

    @classmethod
    def _strip_filter_nodes(cls, plan):
        """Remove Filter nodes from the plan tree without applying them."""
        if isinstance(plan, Scan): return plan
        if isinstance(plan, Join):
            raise RuntimeError("_strip_filter_nodes: Join should have been materialized")
        if isinstance(plan, Filter):
            return cls._strip_filter_nodes(plan.input)
        if isinstance(plan, Project):
            return Project(cls._strip_filter_nodes(plan.input), plan.exprs)
        if isinstance(plan, Aggregate):
            return Aggregate(cls._strip_filter_nodes(plan.input), plan.group_by, plan.aggs)
        if isinstance(plan, Sort):
            return Sort(cls._strip_filter_nodes(plan.input), plan.by, plan.descending)
        if isinstance(plan, Limit):
            return Limit(cls._strip_filter_nodes(plan.input), plan.n)
        if isinstance(plan, Distinct):
            return Distinct(cls._strip_filter_nodes(plan.input), plan.subset)
        if hasattr(plan, 'input'):
            plan.input = cls._strip_filter_nodes(plan.input)
        return plan

    def compile_and_run(self, plan, verbose=False, optimizer_trace=None) -> pa.Table:
        """Optimized execution with three-tier caching + post-ops.

        Pipeline:
        -1. Materialize any Join nodes (recursive, bottom-up).
        0. Extract post-ops (Sort/Limit/Distinct) from top of plan.
        1. Check input-prep cache; on hit skip to step 5.
        2. Pre-encode group keys on original table (cached).
        3. Compute filter mask as numpy boolean array.
        4. Apply mask via numpy boolean indexing; store in prep cache.
        5. Look up / compile cached MAX Graph model.
        6. Execute model and assemble output.
        7. Apply post-ops via Mojo kernels.
        """
        t0 = _time.perf_counter()

        # -1 -- Materialize Join nodes (bottom-up) --------------------
        plan = self._materialize_joins(plan)

        # 0 -- Extract post-ops (Sort/Limit/Distinct) -----------------
        plan, post_ops = self._extract_post_ops(plan)

        # 0a -- Extract HAVING filter: a Filter wrapping an Aggregate is HAVING,
        # not a pre-scan WHERE.  Pull it out and apply after aggregation.
        having_pred = None
        if isinstance(plan, Filter):
            inner_no_filt = self._strip_filter_nodes(plan.input)
            if self._find_aggregate(inner_no_filt) is not None:
                having_pred = plan.predicate
                plan = plan.input

        # 0b -- No-compute shortcut: when plan has no Aggregate/Project,
        # process in PyArrow (preserving all column types including strings).
        plan_no_filters = self._strip_filter_nodes(plan)
        if self._find_aggregate(plan_no_filters) is None:
            # No Aggregate: use PyArrow path (handles strings, year, Project, Filter)
            result = self._plan_to_table(plan)
            if post_ops:
                result = self._apply_post_ops_custom(result, post_ops)
            t1 = _time.perf_counter()
            self.last_compile_provenance = {
                "device": self._session_device,
                "rows": int(result.num_rows),
                "grouped": False,
                "n_groups": 0,
                "cache_hit": None,
                "compile_ms": 0.0,
                "execute_ms": round((t1 - t0) * 1000, 1),
                "gpu_input_path": "pyarrow",
                "optimizer_trace": list(optimizer_trace or []),
                "path": "pyarrow_shortcut",
            }
            if verbose:
                print(f"[mxframe] PyArrow shortcut — {(t1-t0)*1000:.1f}ms")
            return result

        # 1b2 -- Global aggregate shortcut: bypass MAX Engine for un-grouped aggs.
        # ops.sum / max / etc. on GPU is unreliable; PyArrow+numpy is faster for
        # the small joined-table sizes typical of TPC-H Q14-style queries.
        _agg_check = self._find_aggregate(self._strip_filter_nodes(plan))
        if _agg_check is not None and not _agg_check.group_by:
            _agg_orig  = self._find_aggregate(plan)
            _inner_tbl = self._plan_to_table(_agg_orig.input)
            result     = self._compute_global_agg_pyarrow(_inner_tbl, _agg_orig)
            if post_ops:
                result = self._apply_post_ops_custom(result, post_ops)
            t1 = _time.perf_counter()
            self.last_compile_provenance = {
                "device": self._session_device, "rows": 1,
                "grouped": False, "n_groups": 0, "cache_hit": False,
                "compile_ms": 0.0,
                "execute_ms": round((t1 - t0) * 1000, 1),
                "gpu_input_path": "pyarrow",
                "optimizer_trace": list(optimizer_trace or []),
                "path": "global_agg_pyarrow",
            }
            return result

        # 1 -- Resolve plan, predicates, and decide execution path -----
        original_scan = self._find_scan(plan)
        plan_clean = self._strip_filter_nodes(plan)
        predicates = self._collect_predicates(plan)

        # 1b -- Rewrite case_when/isin/startswith as derived col refs (before prep_key).
        plan_clean, derived_specs = self._extract_derived_cols(plan_clean)

        # GPU filter path: when on GPU and ALL predicates are numeric comparisons,
        # skip per-column CPU boolean-indexing. Upload full (unfiltered) arrays once
        # and cache them; pass a small int32 mask per query. The compiled MAX Graph
        # is reused across all filter values on the same table.
        on_gpu = (self._session_device == "gpu") or (
            self._device_arg == "auto" and self._has_gpu
            and original_scan.table.num_rows > AUTO_GPU_THRESHOLD
        )
        use_gpu_filter = (
            on_gpu
            and bool(predicates)
            and all(self._can_compile_predicate_gpu(p) for p in predicates)
        )

        # pred_sig is empty for GPU filter path: graph is reused across filter values.
        pred_sig = () if use_gpu_filter else tuple(p.signature() for p in predicates)
        prep_key = (id(original_scan.table), original_scan.table.num_rows,
                    plan_clean.signature(), pred_sig, self._session_device)

        # 2 -- Check input-prep cache (fastest main path) --------------
        cached_prep = _INPUT_PREP_CACHE.get(prep_key)
        if cached_prep is not None:
            col_names = cached_prep['col_names']
            col_arrays = cached_prep['col_arrays']
            extra_inputs = cached_prep['extra_inputs']
            n_groups = cached_prep['n_groups']
            unique_key_cols = cached_prep['unique_key_cols']
            group_keys = cached_prep['group_keys']
            N = cached_prep['N']
            _group_ids_full = cached_prep.get('_group_ids_full')
            self._N = N
            self._maybe_switch_device(N)
        else:
            # 3 -- Pre-encode group keys on ORIGINAL table (cached) ----
            agg_node = self._find_aggregate(plan_clean)
            group_keys = []
            n_groups = 0
            unique_key_cols = {}
            group_ids_full = None
            _group_ids_full = None

            if agg_node is not None and agg_node.group_by:
                group_keys = [e.args[0] for e in agg_node.group_by]
                group_ids_full, n_groups, unique_key_cols = self._build_group_ids_cached(
                    original_scan.table, group_keys, gpu_compiler=self
                )

            if use_gpu_filter:
                # 4a -- GPU filter path: full arrays, no per-column CPU copy ----
                # Columns are uploaded once and cached on GPU. Only the int32 mask
                # (computed from the predicate) changes per query.
                N = original_scan.table.num_rows
                self._N = N
                self._maybe_switch_device(N)
                extra_inputs = {}
                if group_ids_full is not None:
                    extra_inputs["__group_ids__"] = group_ids_full
                col_names = []
                col_arrays = {}
                for name in original_scan.table.column_names:
                    if not self._is_numeric_arrow_type(
                        original_scan.table.schema.field(name).type
                    ):
                        continue
                    np_arr, _, _ = self._column_to_numpy_cached(original_scan.table.column(name))
                    if np_arr is None:
                        continue
                    col_names.append(name)
                    col_arrays[name] = np_arr
                # 4a-derived: pre-compute case_when/isin/startswith (unmasked on GPU)
                for deriv_name, deriv_expr in derived_specs:
                    arr = self._eval_expr_arrow(deriv_expr, original_scan.table)
                    col_arrays[deriv_name] = arr.to_numpy(zero_copy_only=False).astype(np.float32)
                    col_names.append(deriv_name)
                _group_ids_full = group_ids_full
                _INPUT_PREP_CACHE[prep_key] = {
                    'col_names': col_names, 'col_arrays': col_arrays,
                    'extra_inputs': extra_inputs, 'n_groups': n_groups,
                    'unique_key_cols': unique_key_cols, 'group_keys': group_keys,
                    'N': N, '_group_ids_full': group_ids_full,
                }
            else:
                # 4b -- Standard CPU filter path -----------------------
                mask_np = None
                if predicates:
                    combined = None
                    for pred in predicates:
                        m = self._eval_predicate(pred, original_scan.table)
                        combined = m if combined is None else pc.and_(combined, m)
                    mask_np = combined.to_numpy(zero_copy_only=False)

                N = int(mask_np.sum()) if mask_np is not None else original_scan.table.num_rows
                self._N = N
                self._maybe_switch_device(N)

                extra_inputs = {}
                if group_ids_full is not None:
                    gids = group_ids_full[mask_np] if mask_np is not None else group_ids_full
                    if mask_np is not None:
                        groups_present = np.zeros(n_groups, dtype=bool)
                        groups_present[gids] = True
                        if not groups_present.all():
                            present_idx = np.where(groups_present)[0]
                            remap = np.empty(n_groups, dtype=np.int32)
                            remap[present_idx] = np.arange(len(present_idx), dtype=np.int32)
                            gids = remap[gids]
                            n_groups = len(present_idx)
                            unique_key_cols = {
                                k: v.take(pa.array(present_idx.astype(np.int64)))
                                for k, v in unique_key_cols.items()
                            }
                    extra_inputs["__group_ids__"] = gids

                col_names = []
                col_arrays = {}
                for name in original_scan.table.column_names:
                    if not self._is_numeric_arrow_type(
                        original_scan.table.schema.field(name).type
                    ):
                        continue
                    np_arr, _, _ = self._column_to_numpy_cached(original_scan.table.column(name))
                    if np_arr is None:
                        continue
                    if mask_np is not None:
                        np_arr = np_arr[mask_np]
                    col_names.append(name)
                    col_arrays[name] = np_arr

                # 4b-derived: pre-compute case_when/isin/startswith, then apply mask
                for deriv_name, deriv_expr in derived_specs:
                    arr = self._eval_expr_arrow(deriv_expr, original_scan.table)
                    np_arr = arr.to_numpy(zero_copy_only=False).astype(np.float32)
                    if mask_np is not None:
                        np_arr = np_arr[mask_np]
                    col_arrays[deriv_name] = np_arr
                    col_names.append(deriv_name)

                _INPUT_PREP_CACHE[prep_key] = {
                    'col_names': col_names, 'col_arrays': col_arrays,
                    'extra_inputs': extra_inputs, 'n_groups': n_groups,
                    'unique_key_cols': unique_key_cols, 'group_keys': group_keys,
                    'N': N,
                }

        # GPU filter path: compute fresh int32 mask per query (query-specific, not cached).
        # The mask is small relative to column data; stable columns are reused from cache.
        mask_np_int32 = None
        if use_gpu_filter and predicates:
            combined_pred = predicates[0]
            for p in predicates[1:]:
                combined_pred = Expr("and", combined_pred, p)
            arrow_mask = self._eval_predicate(combined_pred, original_scan.table)
            mask_np_int32 = arrow_mask.to_numpy(zero_copy_only=False).astype(np.int32)

        all_names = col_names + list(extra_inputs.keys())
        all_arrays = {**col_arrays, **extra_inputs}
        if mask_np_int32 is not None:
            all_names = all_names + ["__filter_mask__"]
            all_arrays["__filter_mask__"] = mask_np_int32

        # 5 -- Graph cache lookup --------------------------------------
        cache_key = self._compute_cache_key(
            plan_clean,
            all_names,
            all_arrays,
            n_groups,
            optimizer_trace=optimizer_trace,
        )
        cache_hit = cache_key in _MODEL_CACHE

        if cache_hit:
            model, agg_names = _MODEL_CACHE[cache_key]
            t_compile = _time.perf_counter()
        else:
            if verbose:
                print("[mxframe] Compiling query plan...", end=" ", flush=True)

            input_types = [
                TensorType(_max_dtype(all_arrays[n]), list(all_arrays[n].shape), self._device_ref)
                for n in all_names
            ]

            graph = Graph(
                name="mxframe_custom",
                input_types=input_types,
                custom_extensions=[Path(self.kernels_path)],
            )
            with graph:
                nodes = {n: graph.inputs[i] for i, n in enumerate(all_names)}
                result_nodes = self._visit_plan_custom(plan_clean, nodes, n_groups=n_groups)
                graph.output(*result_nodes.values())

            model = self.session.load(graph)
            agg_names = list(result_nodes.keys())
            _MODEL_CACHE[cache_key] = (model, agg_names)
            t_compile = _time.perf_counter()

        # 6 -- Execute (with GPU buffer cache) ------------------------
        # Stable inputs (everything except __filter_mask__) are cached as
        # driver.Buffer objects so repeated queries on the same data skip
        # the PCIe upload entirely. __filter_mask__ is query-specific and
        # always re-uploaded (it is small: N * 4 bytes).
        gpu_input_path = "cpu_numpy"
        if self._session_device == "gpu":
            stable_names = [n for n in all_names if n != "__filter_mask__"]
            cached_bufs = _GPU_BUFFER_CACHE.get(prep_key)
            execute_inputs = []
            if cached_bufs is not None and all(n in cached_bufs for n in stable_names):
                for n in all_names:
                    if n == "__filter_mask__":
                        mask_buf, _ = self._to_gpu_input(all_arrays[n])
                        execute_inputs.append(mask_buf)
                    else:
                        execute_inputs.append(cached_bufs[n])
                gpu_input_path = "gpu_cached"
            else:
                new_bufs: Dict[str, Any] = {}
                for n in all_names:
                    gpu_buf, path_used = self._to_gpu_input(all_arrays[n])
                    execute_inputs.append(gpu_buf)
                    if n != "__filter_mask__":
                        new_bufs[n] = gpu_buf
                _GPU_BUFFER_CACHE[prep_key] = new_bufs
                gpu_input_path = "uploaded"
        else:
            execute_inputs = [all_arrays[n] for n in all_names]

        output_vals = model.execute(*execute_inputs)
        t_exec = _time.perf_counter()

        if verbose:
            compile_ms = (t_compile - t0) * 1000
            exec_ms = (t_exec - t_compile) * 1000
            total_ms = (t_exec - t0) * 1000
            if cache_hit:
                print(f"[mxframe] Cache hit. Executed on {self._session_device.upper()} in "
                      f"{total_ms:.1f}ms (data prep: {compile_ms:.1f}ms, execute: {exec_ms:.1f}ms)")
            else:
                print(f"done in {total_ms:.1f}ms "
                      f"(compile: {compile_ms:.1f}ms, execute: {exec_ms:.1f}ms). "
                      f"Next run with same schema: ~{exec_ms:.0f}ms")

        self.last_compile_provenance = {
            "device": self._session_device,
            "rows": int(N),
            "grouped": bool(group_keys),
            "n_groups": int(n_groups),
            "cache_hit": cache_hit,
            "compile_ms": round((t_compile - t0) * 1000, 1),
            "execute_ms": round((t_exec - t_compile) * 1000, 1),
            "gpu_input_path": gpu_input_path,
            "optimizer_trace": list(optimizer_trace or []),
            "path": "compiled",
            "gpu_filter": use_gpu_filter,
        }

        # 7 -- Assemble output ----------------------------------------
        agg_arrays = [pa.array(np.asarray(t.to_numpy()).reshape(-1)) for t in output_vals]

        if unique_key_cols:
            if (use_gpu_filter and group_keys
                    and mask_np_int32 is not None and _group_ids_full is not None):
                # Groups whose rows were all masked out produce silent zeros in the
                # kernel output. Remove them so they don't appear in the result.
                surviving = np.zeros(n_groups, dtype=bool)
                surviving[_group_ids_full[mask_np_int32.astype(bool)]] = True
                if not surviving.all():
                    surv_filter = pa.array(surviving)
                    unique_key_cols = {k: v.filter(surv_filter) for k, v in unique_key_cols.items()}
                    agg_arrays = [arr.filter(surv_filter) for arr in agg_arrays]
            key_arrays = [unique_key_cols[k] for k in group_keys]
            result = pa.Table.from_arrays(key_arrays + agg_arrays, names=group_keys + agg_names)
        else:
            result = pa.Table.from_arrays(agg_arrays, names=agg_names)

        # 8 -- Apply HAVING filter (post-aggregation predicate) -------
        if having_pred is not None:
            having_mask = self._eval_predicate(having_pred, result)
            result = result.filter(having_mask)

        # 9 -- Apply post-ops (Sort/Limit/Distinct via Mojo kernels) ---
        if post_ops:
            result = self._apply_post_ops_custom(result, post_ops)

        return result

    def _visit_plan_custom(self, plan, nodes, *, n_groups=0):
        if isinstance(plan, Scan):
            return nodes
        elif isinstance(plan, Project):
            upstream = self._visit_plan_custom(plan.input, nodes, n_groups=n_groups)
            out = {}
            for i, expr in enumerate(plan.exprs):
                name = expr._alias or f'col_{i}'
                out[name] = self._visit_expr(expr, upstream)
            return out
        elif isinstance(plan, Filter):
            raise RuntimeError(
                'Filter node reached _visit_plan_custom -- '
                '_strip_filters should have removed all Filter nodes.'
            )
        elif isinstance(plan, (Sort, Limit, Distinct)):
            # Post-ops: should have been extracted by _extract_post_ops.
            # If they reach here, just recurse through to inner plan.
            return self._visit_plan_custom(plan.input, nodes, n_groups=n_groups)
        elif isinstance(plan, Aggregate):
            return self._visit_aggregate_custom(plan, nodes, n_groups=n_groups)
        raise NotImplementedError(f'Unsupported plan node: {type(plan)}')

    def _visit_aggregate_custom(self, plan, nodes, *, n_groups):
        upstream = self._visit_plan_custom(plan.input, nodes, n_groups=n_groups)
        out = {}
        grouped = bool(plan.group_by)
        on_gpu = (self._session_device == "gpu")

        for i, expr in enumerate(plan.aggs):
            name = expr._alias or f'agg_{i}'
            if grouped and n_groups > 0:
                gid_raw = ops.cast(upstream["__group_ids__"], DType.int32)

                if "__filter_mask__" in upstream:
                    # GPU filter path: encode filtered-out rows as gid = -1.
                    # Existing kernels already check `gid >= 0`, so they naturally
                    # skip rows where the predicate is false — no kernel changes needed.
                    # Formula: effective_gid = (gid + 1) * mask - 1
                    #   mask=1 → (gid+1)*1 - 1 = gid  (process)
                    #   mask=0 → (gid+1)*0 - 1 = -1   (skip)
                    mask_i32 = ops.cast(upstream["__filter_mask__"], DType.int32)
                    one = ops.constant(1, dtype=DType.int32, device=self._device_ref)
                    gid_node = ops.sub(
                        ops.mul(ops.add(gid_raw, one), mask_i32),
                        one,
                    )
                else:
                    gid_node = gid_raw

                # Both GPU and CPU kernels write final aggregated results directly
                # to an output tensor of shape [n_groups] using atomic adds.
                # On GPU: shared-mem privatization up to MAX_GROUPS (8192), then
                # global-atomic fallback — no cardinality ceiling.
                out_type = TensorType(DType.float32, [n_groups], self._device_ref)

                if on_gpu and n_groups <= 0:
                    raise ValueError(
                        f"Grouped GPU path requires n_groups > 0; got {n_groups}."
                    )

                if expr.op == "count":
                    out[name] = ops.custom(
                        name="group_count",
                        values=[gid_node],
                        out_types=[out_type],
                        device=self._device_ref,
                    )[0]
                elif expr.op in ("sum", "min", "max", "mean"):
                    val_node = ops.cast(self._visit_expr(expr.args[0], upstream), DType.float32)
                    if expr.op == "mean":
                        sum_node = ops.custom(
                            name="group_sum",
                            values=[val_node, gid_node],
                            out_types=[out_type],
                            device=self._device_ref,
                        )[0]
                        cnt_node = ops.custom(
                            name="group_count",
                            values=[gid_node],
                            out_types=[out_type],
                            device=self._device_ref,
                        )[0]
                        out[name] = ops.div(sum_node, ops.cast(cnt_node, DType.float32))
                    else:
                        out[name] = ops.custom(
                            name=f"group_{expr.op}",
                            values=[val_node, gid_node],
                            out_types=[out_type],
                            device=self._device_ref,
                        )[0]
                else:
                    raise NotImplementedError(
                        f"Grouped '{expr.op}' is not yet supported. "
                        f"Add a group_{expr.op}.mojo kernel and wire it."
                    )
            else:
                out[name] = self._visit_expr(expr, upstream)
        return out

    @staticmethod
    def _find_aggregate(plan):
        if isinstance(plan, Aggregate): return plan
        if hasattr(plan, 'input'): return CustomOpsCompiler._find_aggregate(plan.input)
        return None

    # -- Sort / Limit / Distinct via Mojo kernels ----------------------

    def _encode_sort_key(self, table: pa.Table, by_exprs, descending: list) -> np.ndarray:
        """Dictionary-encode sort key columns into a single int32 composite key.

        Each sort key column is dictionary-encoded to contiguous int32 indices,
        then remapped so that ascending index = lexicographic order.
        For multi-key sorts, indices are composed with strides so that the
        composite integer has the correct lexicographic ordering.
        For descending keys, the index is flipped so ascending sort -> descending.
        """
        key_names = [e.args[0] for e in by_exprs]
        encodings = []
        for k in key_names:
            arr = table.column(k)
            if isinstance(arr, pa.ChunkedArray):
                arr = arr.combine_chunks()
            encodings.append(arr.dictionary_encode())

        sizes = [len(e.dictionary) for e in encodings]

        # Compute strides for lexicographic composite key
        strides = []
        for i in range(len(sizes)):
            s = 1
            for j in range(i + 1, len(sizes)):
                s *= sizes[j]
            strides.append(s)

        composite = np.zeros(len(table), dtype=np.int32)
        for i, enc in enumerate(encodings):
            # Remap dictionary indices so ascending index = lexicographic order.
            # dictionary_encode() gives encounter-order, not sorted-order.
            dict_arr = enc.dictionary
            sorted_order = pc.sort_indices(dict_arr).to_numpy(zero_copy_only=False)
            # sorted_order[rank] = original_dict_idx  ->  we need rank_of[original_dict_idx] = rank
            rank_of = np.empty(len(dict_arr), dtype=np.int32)
            for r, orig_idx in enumerate(sorted_order):
                rank_of[orig_idx] = r
            raw_idx = enc.indices.to_numpy(zero_copy_only=False).astype(np.int32)
            idx = rank_of[raw_idx]
            if descending[i]:
                idx = (sizes[i] - 1) - idx  # flip so ascending sort -> descending
            composite += idx * strides[i]
        return composite

    def _apply_sort_custom(self, table: pa.Table, sort_node: Sort) -> pa.Table:
        """Sort an Arrow table by integer composite key.

        CPU: pure numpy argsort -- no MAX Graph overhead.
        GPU: Mojo bitonic sort kernel via MAX Graph, model cached by N.
        """
        composite_key = self._encode_sort_key(table, sort_node.by, sort_node.descending)
        N = len(composite_key)

        if self._session_device != "gpu":
            # CPU fast path: numpy argsort, no graph compilation
            sorted_indices = np.argsort(composite_key, kind='stable')
            return table.take(pa.array(sorted_indices.astype(np.int64)))
        else:
            # GPU path: Mojo bitonic sort, model cached by N
            cache_key = ("sort_indices", N, self._session_device)
            model = _POST_OP_MODEL_CACHE.get(cache_key)
            if model is None:
                key_type = TensorType(DType.int32, [N], self._device_ref)
                flag_type = TensorType(DType.int32, [1], self._device_ref)
                graph = Graph(
                    name="mxframe_sort",
                    input_types=[key_type, flag_type],
                    custom_extensions=[Path(self.kernels_path)],
                )
                with graph:
                    indices = ops.custom(
                        name="sort_indices",
                        values=[graph.inputs[0], graph.inputs[1]],
                        out_types=[TensorType(DType.int32, [N], self._device_ref)],
                        device=self._device_ref,
                    )[0]
                    graph.output(indices)
                model = self.session.load(graph)
                _POST_OP_MODEL_CACHE[cache_key] = model
            desc_flag = np.array([0], dtype=np.int32)
            k_buf = driver.Buffer.from_numpy(composite_key).to(self._gpu_driver)
            f_buf = driver.Buffer.from_numpy(desc_flag).to(self._gpu_driver)
            (out_idx,) = model.execute(k_buf, f_buf)
            # sorted_indices stays on GPU; use gather_f32/gather_i32 kernels
            # per column to reorder rows without pulling indices back to CPU.
            # Falls back to CPU Arrow.take for non-float32/int32 columns.
            return self._gpu_gather_table(table, out_idx, N)

    def _gpu_gather_table(self, table: pa.Table, idx_tensor, N: int) -> pa.Table:
        """Gather rows of `table` using an index tensor already on GPU.

        For float32 and int32 columns the gather runs on GPU via the
        `gather_f32` / `gather_i32` Mojo kernels.  All other column types
        (strings, dates, booleans, etc.) fall back to a single CPU Arrow.take
        after reading the index tensor once.

        `idx_tensor` is the raw MAX output tensor (still on GPU).
        `N` is the number of rows in `table` (= len(idx_tensor)).
        """
        # Compile / cache a single-column gather model for this N
        def _get_gather_model(dtype_key: str, mojo_name: str, arr_dtype: DType):
            ck = (mojo_name, N, self._session_device)
            m = _POST_OP_MODEL_CACHE.get(ck)
            if m is None:
                val_type = TensorType(arr_dtype, [N], self._device_ref)
                idx_type = TensorType(DType.int32, [N], self._device_ref)
                g = Graph(
                    name=f"mxframe_{mojo_name}",
                    input_types=[val_type, idx_type],
                    custom_extensions=[Path(self.kernels_path)],
                )
                with g:
                    out = ops.custom(
                        name=mojo_name,
                        values=[g.inputs[0], g.inputs[1]],
                        out_types=[TensorType(arr_dtype, [N], self._device_ref)],
                        device=self._device_ref,
                    )[0]
                    g.output(out)
                m = self.session.load(g)
                _POST_OP_MODEL_CACHE[ck] = m
            return m

        # Upload index once and reuse the buffer across all columns
        idx_np = np.asarray(idx_tensor.to_numpy()).reshape(-1).astype(np.int32)
        idx_buf = driver.Buffer.from_numpy(idx_np).to(self._gpu_driver)

        gathered_arrays = []
        gathered_names = []
        cpu_fallback_needed = False
        cpu_fallback_indices = idx_np  # read back only if needed

        for col_name in table.column_names:
            col = table.column(col_name)
            if isinstance(col, pa.ChunkedArray):
                col = col.combine_chunks()

            if pa.types.is_float32(col.type):
                np_col = col.to_numpy(zero_copy_only=False).astype(np.float32)
                model = _get_gather_model("f32", "gather_f32", DType.float32)
                col_buf = driver.Buffer.from_numpy(np_col).to(self._gpu_driver)
                (out_t,) = model.execute(col_buf, idx_buf)
                gathered_arrays.append(pa.array(np.asarray(out_t.to_numpy()).reshape(-1)))
            elif pa.types.is_integer(col.type):
                np_col = col.to_numpy(zero_copy_only=False).astype(np.int32)
                model = _get_gather_model("i32", "gather_i32", DType.int32)
                col_buf = driver.Buffer.from_numpy(np_col).to(self._gpu_driver)
                (out_t,) = model.execute(col_buf, idx_buf)
                gathered_arrays.append(pa.array(np.asarray(out_t.to_numpy()).reshape(-1)))
            else:
                # Non-numeric column: fall back to Arrow.take (index already on CPU)
                gathered_arrays.append(col.take(pa.array(idx_np.astype(np.int64))))
            gathered_names.append(col_name)

        return pa.Table.from_arrays(gathered_arrays, names=gathered_names)

    def _gpu_gather_table_np(self, table: pa.Table, idx_np: np.ndarray, N: int) -> pa.Table:
        """Like _gpu_gather_table but accepts a numpy index array directly.

        Used in _execute_hash_join on the GPU path: the join kernels already return
        numpy int32 index arrays, so we skip the idx_tensor.to_numpy() step of
        _gpu_gather_table.  For float32/int32 columns the gather runs on GPU via the
        'gather_f32' / 'gather_i32' Mojo kernels; string/date columns fall back to
        PyArrow .take() on CPU.
        """
        def _get_gather_model(mojo_name: str, arr_dtype: DType, source_len: int):
            # Cache key includes source_len: source table size determines graph input
            # type for position 0; different table sizes require different compiled models.
            ck = (mojo_name, source_len, N, self._session_device)
            m = _POST_OP_MODEL_CACHE.get(ck)
            if m is None:
                val_type = TensorType(arr_dtype, [source_len], self._device_ref)
                idx_type = TensorType(DType.int32, [N], self._device_ref)
                g = Graph(
                    name=f"mxframe_{mojo_name}",
                    input_types=[val_type, idx_type],
                    custom_extensions=[Path(self.kernels_path)],
                )
                with g:
                    out = ops.custom(
                        name=mojo_name,
                        values=[g.inputs[0], g.inputs[1]],
                        out_types=[TensorType(arr_dtype, [N], self._device_ref)],
                        device=self._device_ref,
                    )[0]
                    g.output(out)
                m = self.session.load(g)
                _POST_OP_MODEL_CACHE[ck] = m
            return m

        idx_int32 = idx_np.astype(np.int32)
        idx_buf = driver.Buffer.from_numpy(idx_int32).to(self._gpu_driver)

        gathered_arrays = []
        gathered_names = []
        for col_name in table.column_names:
            col = table.column(col_name)
            if isinstance(col, pa.ChunkedArray):
                col = col.combine_chunks()
            source_len = len(col)
            if pa.types.is_float32(col.type):
                model = _get_gather_model("gather_f32", DType.float32, source_len)
                col_buf = driver.Buffer.from_numpy(
                    col.to_numpy(zero_copy_only=False).astype(np.float32)
                ).to(self._gpu_driver)
                (out_t,) = model.execute(col_buf, idx_buf)
                gathered_arrays.append(pa.array(np.asarray(out_t.to_numpy()).reshape(-1)))
            elif pa.types.is_integer(col.type):
                model = _get_gather_model("gather_i32", DType.int32, source_len)
                col_buf = driver.Buffer.from_numpy(
                    col.to_numpy(zero_copy_only=False).astype(np.int32)
                ).to(self._gpu_driver)
                (out_t,) = model.execute(col_buf, idx_buf)
                gathered_arrays.append(pa.array(np.asarray(out_t.to_numpy()).reshape(-1)))
            else:
                # Non-numeric column (string, date, etc.): CPU fallback
                gathered_arrays.append(col.take(pa.array(idx_int32.astype(np.int64))))
            gathered_names.append(col_name)

        return pa.Table.from_arrays(gathered_arrays, names=gathered_names)

    def _apply_distinct_custom(self, table, distinct_node):
        cols = distinct_node.subset or table.column_names
        return table.group_by(cols).aggregate([])

    def _apply_post_ops_custom(self, table: pa.Table, post_ops: list) -> pa.Table:
        """Apply Sort/Limit/Distinct using Mojo kernels (not PyArrow compute)."""
        for node in post_ops:
            if isinstance(node, Sort):
                table = self._apply_sort_custom(table, node)
            elif isinstance(node, Limit):
                table = table.slice(0, node.n)
            elif isinstance(node, Distinct):
                table = self._apply_distinct_custom(table, node)
        return table


    # -- Join materialization ------------------------------------------

    @staticmethod
    def _plan_stable_key(plan) -> tuple | None:
        """Return a stable, hashable key for a join-free Filter→Scan chain.

        Used to cache join results across repeated .compute() calls on the same
        input tables with identical filter predicates.  Returns None for plans
        that are too complex to cheaply fingerprint (nested joins, projections, …).
        """
        if isinstance(plan, Scan):
            return (id(plan.table), plan.table.num_rows)
        if isinstance(plan, Filter):
            inner = CustomOpsCompiler._plan_stable_key(plan.input)
            if inner is None:
                return None
            return inner + (plan.predicate.signature(),)
        return None

    def _materialize_joins(self, plan):
        """Recursively replace Join nodes with Scan(joined_table).

        Walks bottom-up: materializes both sides of a Join, executes the
        hash join (Mojo kernel or numpy), and returns a Scan of the result.
        After this, the plan tree is a single-input chain again.

        Join results are cached in _JOIN_RESULT_CACHE keyed by the stable
        fingerprints of both input plans + join columns.  This eliminates
        redundant join computation on hot calls where the input tables are
        the same Python objects.
        """
        if isinstance(plan, Scan):
            return plan
        if isinstance(plan, Join):
            left_plan = self._materialize_joins(plan.left)
            right_plan = self._materialize_joins(plan.right)

            # Attempt join-result cache lookup before materialising tables.
            left_key  = self._plan_stable_key(left_plan)
            right_key = self._plan_stable_key(right_plan)
            join_cache_key: tuple | None = None
            if left_key is not None and right_key is not None:
                join_cache_key = (
                    left_key, right_key,
                    tuple(plan.left_on), tuple(plan.right_on),
                    plan.how,
                )
                cached_join = _JOIN_RESULT_CACHE.get(join_cache_key)
                if cached_join is not None:
                    return Scan(cached_join)

            left_table = self._plan_to_table(left_plan)
            right_table = self._plan_to_table(right_plan)
            joined = self._execute_hash_join(
                left_table, right_table, plan.left_on, plan.right_on, how=plan.how
            )
            if join_cache_key is not None:
                _JOIN_RESULT_CACHE[join_cache_key] = joined
            return Scan(joined)
        if isinstance(plan, Filter):
            return Filter(self._materialize_joins(plan.input), plan.predicate)
        if isinstance(plan, Project):
            return Project(self._materialize_joins(plan.input), plan.exprs)
        if isinstance(plan, Aggregate):
            return Aggregate(self._materialize_joins(plan.input), plan.group_by, plan.aggs)
        if isinstance(plan, Sort):
            return Sort(self._materialize_joins(plan.input), plan.by, plan.descending)
        if isinstance(plan, Limit):
            return Limit(self._materialize_joins(plan.input), plan.n)
        if isinstance(plan, Distinct):
            return Distinct(self._materialize_joins(plan.input), plan.subset)
        if hasattr(plan, 'input'):
            plan.input = self._materialize_joins(plan.input)
        return plan

    def _plan_to_table(self, plan) -> pa.Table:
        """Resolve a plan subtree (no Aggregate) to a concrete pa.Table via PyArrow.

        Handles:
        - Scan: return table directly
        - Filter → ... → Scan: apply predicates eagerly in PyArrow
        - Project: evaluate all exprs via _eval_expr_arrow (handles strings, year, etc.)
        - Anything complex: delegate to compile_and_run
        """
        if isinstance(plan, Scan):
            return plan.table
        if isinstance(plan, Filter):
            inner_table = self._plan_to_table(plan.input)
            mask = self._eval_predicate(plan.predicate, inner_table)
            return inner_table.filter(mask)
        if isinstance(plan, Project):
            inner_table = self._plan_to_table(plan.input)
            arrays, names = [], []
            for expr in plan.exprs:
                arr = self._eval_expr_arrow(expr, inner_table)
                name = expr._alias or (expr.args[0] if expr.op == "col" else f"col_{len(arrays)}")
                arrays.append(arr)
                names.append(name)
            return pa.Table.from_arrays(arrays, names=names)
        # For anything more complex (Aggregate etc.), use the full compiler
        return self.compile_and_run(plan)

    def _execute_hash_join(self, left_table, right_table, left_on, right_on, how="inner"):
        """Execute a hash join: inner via Mojo, left outer via PyArrow.

        how="inner": Mojo GPU/CPU kernels, all matching rows.
        how="left":  PyArrow left outer; unmatched left rows get null right cols.
        """
        if how == "left":
            right_cols = [c for c in right_table.column_names if c not in right_on]
            joined = left_table.join(
                right_table, keys=left_on, right_keys=right_on,
                join_type="left outer", right_suffix="_right", coalesce_keys=True,
            )
            keep = [c for c in left_table.column_names + right_cols if c in joined.column_names]
            return joined.select(keep)

        # inner join via Mojo kernels
        left_keys = self._encode_join_keys(left_table, left_on)
        right_keys = self._encode_join_keys(right_table, right_on)

        # Route by session device: GPU join kernels for GPU sessions,
        # CPU join kernels for CPU sessions.
        if self._session_device == "gpu":
            left_idx, right_idx = self._hash_join_mojo_gpu(left_keys, right_keys)
        else:
            left_idx, right_idx = self._hash_join_mojo_cpu(left_keys, right_keys)

        n_result = len(left_idx)

        # Assemble joined table.
        # For GPU sessions with large results: use GPU gather kernels for float32/int32
        # columns to keep numeric data on-device and reduce re-upload before aggregation.
        # For CPU sessions or small results: fast PyArrow .take().
        if self._session_device == "gpu" and n_result > GPU_JOIN_THRESHOLD:
            left_take = self._gpu_gather_table_np(left_table, left_idx, n_result)
            right_take = self._gpu_gather_table_np(right_table, right_idx, n_result)
        else:
            left_take = left_table.take(pa.array(left_idx.astype(np.int64)))
            right_take = right_table.take(pa.array(right_idx.astype(np.int64)))

        # Combine: all left columns + right columns excluding join keys
        arrays = []
        names = []
        for col_name in left_table.column_names:
            arrays.append(left_take.column(col_name))
            names.append(col_name)
        for col_name in right_table.column_names:
            if col_name not in right_on:
                arrays.append(right_take.column(col_name))
                names.append(col_name)

        return pa.Table.from_arrays(arrays, names=names)

    @staticmethod
    def _encode_join_keys(table, key_cols):
        """Encode join key columns into a single int32 numpy array.

        For single integer key: extract directly.
        For multi-key or non-integer: composite encode via dictionary encoding.
        """
        if len(key_cols) == 1:
            arr = table.column(key_cols[0])
            if isinstance(arr, pa.ChunkedArray):
                arr = arr.combine_chunks()
            # If already integer type, use directly
            if pa.types.is_integer(arr.type):
                return arr.to_numpy(zero_copy_only=False).astype(np.int32)
            # For non-integer, dictionary encode
            enc = arr.dictionary_encode()
            return enc.indices.to_numpy(zero_copy_only=False).astype(np.int32)

        # Multi-key: composite encoding (same approach as groupby)
        encodings = []
        for k in key_cols:
            arr = table.column(k)
            if isinstance(arr, pa.ChunkedArray):
                arr = arr.combine_chunks()
            encodings.append(arr.dictionary_encode())

        sizes = [len(e.dictionary) for e in encodings]
        strides = []
        for i in range(len(sizes)):
            s = 1
            for j in range(i + 1, len(sizes)):
                s *= sizes[j]
            strides.append(s)

        # Use int64 to avoid overflow when strides are large (many-column groupby)
        composite = np.zeros(len(table), dtype=np.int64)
        for i, enc in enumerate(encodings):
            idx = enc.indices.to_numpy(zero_copy_only=False).astype(np.int64)
            composite += idx * np.int64(strides[i])
        return composite

    @staticmethod
    def _hash_join_numpy(left_keys: np.ndarray, right_keys: np.ndarray):
        """Session-free fully vectorized inner hash join using NumPy sort + searchsorted.

        Used on GPU sessions with small/medium inputs where Mojo GPU join kernels would
        incur more PCIe round-trip overhead than the join itself costs on CPU.
        All operations are vectorized (no Python loops) - O(n log n) time.
        """
        # Sort right side once
        right_order = np.argsort(right_keys, kind='stable').astype(np.int32)
        sorted_right = right_keys[right_order]

        # For each left key find the matching range [lo, hi) in sorted right
        lo = np.searchsorted(sorted_right, left_keys, side='left')
        hi = np.searchsorted(sorted_right, left_keys, side='right')
        counts = (hi - lo).astype(np.int64)

        n_out = int(counts.sum())
        if n_out == 0:
            return np.empty(0, dtype=np.int32), np.empty(0, dtype=np.int32)

        # Build left_out: each left key repeated counts[i] times
        left_out = np.repeat(
            np.arange(len(left_keys), dtype=np.int32), counts
        )

        # Build right_out: fully vectorized using cumsum offsets
        # For output row k belonging to left_key j:
        #   right index = right_order[lo[j] + relative_position_within_j]
        start_offsets = np.empty(len(left_keys), dtype=np.int64)
        start_offsets[0] = 0
        if len(left_keys) > 1:
            np.cumsum(counts[:-1], out=start_offsets[1:])
        relative_pos = (
            np.arange(n_out, dtype=np.int64)
            - np.repeat(start_offsets, counts)
        )
        right_indexer = lo[left_out].astype(np.int64) + relative_pos
        right_out = right_order[right_indexer].astype(np.int32)

        return left_out, right_out

    def _hash_join_mojo_cpu(self, left_keys, right_keys):
        """CPU path: two-pass hash join via Mojo kernels through MAX Graph.

        Uses join_count_cpu and join_scatter_cpu Mojo kernels — true Mojo-first,
        not numpy.  Returns (left_indices, right_indices) as int32 numpy arrays.
        """
        n_left = len(left_keys)
        n_right = len(right_keys)
        if n_left == 0 or n_right == 0:
            return np.array([], dtype=np.int32), np.array([], dtype=np.int32)

        left_keys_i32 = left_keys.astype(np.int32)
        right_keys_i32 = right_keys.astype(np.int32)

        # -- Pass 1: Count matches via Mojo CPU kernel --
        cache_key_count = ("join_count_cpu", n_left, n_right, self._session_device)
        model_count = _POST_OP_MODEL_CACHE.get(cache_key_count)
        if model_count is None:
            lk_type = TensorType(DType.int32, [n_left], self._device_ref)
            rk_type = TensorType(DType.int32, [n_right], self._device_ref)
            graph = Graph(
                name="mxframe_join_count_cpu",
                input_types=[lk_type, rk_type],
                custom_extensions=[Path(self.kernels_path)],
            )
            with graph:
                match_counts_node = ops.custom(
                    name="join_count_cpu",
                    values=[graph.inputs[0], graph.inputs[1]],
                    out_types=[
                        TensorType(DType.int32, [n_left], self._device_ref),
                    ],
                    device=self._device_ref,
                )[0]
                graph.output(match_counts_node)
            model_count = self.session.load(graph)
            _POST_OP_MODEL_CACHE[cache_key_count] = model_count

        (match_counts_out,) = model_count.execute(left_keys_i32, right_keys_i32)
        match_counts = np.asarray(match_counts_out.to_numpy()).reshape(-1).astype(np.int32)

        # -- Python bridge: total + offsets --
        total = int(match_counts.sum())
        if total == 0:
            return np.array([], dtype=np.int32), np.array([], dtype=np.int32)

        offsets = np.zeros(n_left, dtype=np.int32)
        np.cumsum(match_counts[:-1], out=offsets[1:])

        # -- Pass 2: Scatter via Mojo CPU kernel --
        cache_key_scatter = ("join_scatter_cpu", n_left, n_right, total, self._session_device)
        model_scatter = _POST_OP_MODEL_CACHE.get(cache_key_scatter)
        if model_scatter is None:
            lk_type = TensorType(DType.int32, [n_left], self._device_ref)
            rk_type = TensorType(DType.int32, [n_right], self._device_ref)
            off_type = TensorType(DType.int32, [n_left], self._device_ref)
            graph = Graph(
                name="mxframe_join_scatter_cpu",
                input_types=[lk_type, rk_type, off_type],
                custom_extensions=[Path(self.kernels_path)],
            )
            with graph:
                left_out_node, right_out_node = ops.custom(
                    name="join_scatter_cpu",
                    values=[graph.inputs[0], graph.inputs[1], graph.inputs[2]],
                    out_types=[
                        TensorType(DType.int32, [total], self._device_ref),
                        TensorType(DType.int32, [total], self._device_ref),
                    ],
                    device=self._device_ref,
                )
                graph.output(left_out_node, right_out_node)
            model_scatter = self.session.load(graph)
            _POST_OP_MODEL_CACHE[cache_key_scatter] = model_scatter

        left_out_t, right_out_t = model_scatter.execute(left_keys_i32, right_keys_i32, offsets)
        left_idx = np.asarray(left_out_t.to_numpy()).reshape(-1).astype(np.int32)
        right_idx = np.asarray(right_out_t.to_numpy()).reshape(-1).astype(np.int32)

        return left_idx, right_idx

    def _hash_join_mojo_gpu(self, left_keys, right_keys):
        """GPU path: two-pass hash join via Mojo kernels through MAX Graph.

        Pass 1 (join_count): count matches per left row.
        Python bridge: sum → total, prefix sum → offsets.
        Pass 2 (join_scatter): emit index pairs using pre-built position arrays.
        """
        n_left = len(left_keys)
        n_right = len(right_keys)
        max_key = max(int(left_keys.max()), int(right_keys.max())) if n_left > 0 and n_right > 0 else 0
        table_size = max_key + 1

        left_keys_i32 = left_keys.astype(np.int32)
        right_keys_i32 = right_keys.astype(np.int32)

        # -- Pass 1: Count matches via GPU kernel --
        max_key_buf = np.array([max_key], dtype=np.int32)

        cache_key_count = ("join_count_gpu", n_left, n_right, table_size, self._session_device)
        model_count = _POST_OP_MODEL_CACHE.get(cache_key_count)
        if model_count is None:
            lk_type = TensorType(DType.int32, [n_left], self._device_ref)
            rk_type = TensorType(DType.int32, [n_right], self._device_ref)
            mk_type = TensorType(DType.int32, [1], self._device_ref)
            graph = Graph(
                name="mxframe_join_count",
                input_types=[lk_type, rk_type, mk_type],
                custom_extensions=[Path(self.kernels_path)],
            )
            with graph:
                match_counts_node, right_count_node = ops.custom(
                    name="join_count_gpu",
                    values=[graph.inputs[0], graph.inputs[1], graph.inputs[2]],
                    out_types=[
                        TensorType(DType.int32, [n_left], self._device_ref),
                        TensorType(DType.int32, [table_size], self._device_ref),
                    ],
                    device=self._device_ref,
                )
                graph.output(match_counts_node, right_count_node)
            model_count = self.session.load(graph)
            _POST_OP_MODEL_CACHE[cache_key_count] = model_count

        lk_buf = driver.Buffer.from_numpy(left_keys_i32).to(self._gpu_driver)
        rk_buf = driver.Buffer.from_numpy(right_keys_i32).to(self._gpu_driver)
        mk_buf = driver.Buffer.from_numpy(max_key_buf).to(self._gpu_driver)
        match_counts_out, _ = model_count.execute(lk_buf, rk_buf, mk_buf)
        match_counts = np.asarray(match_counts_out.to_numpy()).reshape(-1).astype(np.int32)

        # -- Python bridge --
        total = int(match_counts.sum())
        if total == 0:
            return np.array([], dtype=np.int32), np.array([], dtype=np.int32)

        offsets = np.zeros(n_left, dtype=np.int32)
        np.cumsum(match_counts[:-1], out=offsets[1:])

        # -- Build right-side position arrays for GPU scatter --
        right_count = np.bincount(right_keys_i32, minlength=table_size).astype(np.int32)
        right_order = np.argsort(right_keys_i32, kind='stable').astype(np.int32)
        right_starts = np.zeros(table_size, dtype=np.int32)
        np.cumsum(right_count[:-1], out=right_starts[1:])

        # -- Pass 2: Scatter via GPU kernel --
        cache_key_scatter = ("join_scatter_gpu", n_left, n_right, total, table_size, self._session_device)
        model_scatter = _POST_OP_MODEL_CACHE.get(cache_key_scatter)
        if model_scatter is None:
            lk_type = TensorType(DType.int32, [n_left], self._device_ref)
            rk_type = TensorType(DType.int32, [n_right], self._device_ref)
            off_type = TensorType(DType.int32, [n_left], self._device_ref)
            rsi_type = TensorType(DType.int32, [n_right], self._device_ref)
            rks_type = TensorType(DType.int32, [table_size], self._device_ref)
            rkc_type = TensorType(DType.int32, [table_size], self._device_ref)
            graph = Graph(
                name="mxframe_join_scatter",
                input_types=[lk_type, rk_type, off_type, rsi_type, rks_type, rkc_type],
                custom_extensions=[Path(self.kernels_path)],
            )
            with graph:
                left_out_node, right_out_node = ops.custom(
                    name="join_scatter_gpu",
                    values=[graph.inputs[0], graph.inputs[1], graph.inputs[2],
                            graph.inputs[3], graph.inputs[4], graph.inputs[5]],
                    out_types=[
                        TensorType(DType.int32, [total], self._device_ref),
                        TensorType(DType.int32, [total], self._device_ref),
                    ],
                    device=self._device_ref,
                )
                graph.output(left_out_node, right_out_node)
            model_scatter = self.session.load(graph)
            _POST_OP_MODEL_CACHE[cache_key_scatter] = model_scatter

        off_buf = driver.Buffer.from_numpy(offsets).to(self._gpu_driver)
        rsi_buf = driver.Buffer.from_numpy(right_order).to(self._gpu_driver)
        rks_buf = driver.Buffer.from_numpy(right_starts).to(self._gpu_driver)
        rkc_buf = driver.Buffer.from_numpy(right_count).to(self._gpu_driver)
        left_out_t, right_out_t = model_scatter.execute(lk_buf, rk_buf, off_buf, rsi_buf, rks_buf, rkc_buf)
        left_idx = np.asarray(left_out_t.to_numpy()).reshape(-1).astype(np.int32)
        right_idx = np.asarray(right_out_t.to_numpy()).reshape(-1).astype(np.int32)

        return left_idx, right_idx

    @staticmethod
    def _build_group_ids(table, keys):
        """Dictionary-encode group keys into contiguous int32 group ids."""
        if len(keys) == 1:
            col_arr = table.column(keys[0])
            if isinstance(col_arr, pa.ChunkedArray):
                col_arr = col_arr.combine_chunks()
            encoded = col_arr.dictionary_encode()
            ids = encoded.indices.to_numpy(zero_copy_only=False).astype(np.int32, copy=False)
            return ids, len(encoded.dictionary), {keys[0]: encoded.dictionary}

        encodings = []
        for k in keys:
            arr = table.column(k)
            if isinstance(arr, pa.ChunkedArray):
                arr = arr.combine_chunks()
            encodings.append(arr.dictionary_encode())

        sizes = [len(e.dictionary) for e in encodings]
        strides = []
        for i in range(len(sizes)):
            s = 1
            for j in range(i + 1, len(sizes)):
                s *= sizes[j]
            strides.append(s)
        max_groups = strides[0] * sizes[0]

        composite = np.zeros(len(table), dtype=np.int32)
        for i, enc in enumerate(encodings):
            idx = enc.indices.to_numpy(zero_copy_only=False)
            composite += (idx * strides[i]).astype(np.int32)

        if max_groups <= 1024:
            present_mask = np.zeros(max_groups, dtype=bool)
            present_mask[composite] = True
            present = np.where(present_mask)[0]
            n_groups = len(present)

            if n_groups == max_groups:
                dense_ids = composite
            else:
                remap = np.empty(max_groups, dtype=np.int32)
                remap[present] = np.arange(n_groups, dtype=np.int32)
                dense_ids = remap[composite]

            unique_key_cols = {}
            for i, k in enumerate(keys):
                key_idx = (present // strides[i]) % sizes[i]
                unique_key_cols[k] = encodings[i].dictionary.take(
                    pa.array(key_idx.astype(np.int64))
                )
            return dense_ids, n_groups, unique_key_cols

        composite_i64 = composite.astype(np.int64)
        unique_composite, dense_ids = np.unique(composite_i64, return_inverse=True)
        dense_ids = dense_ids.astype(np.int32)
        n_groups = len(unique_composite)

        unique_key_cols = {}
        for i, k in enumerate(keys):
            key_idx = ((unique_composite // strides[i]) % sizes[i]).astype(np.int64)
            unique_key_cols[k] = encodings[i].dictionary.take(pa.array(key_idx))

        return dense_ids, n_groups, unique_key_cols

    @staticmethod
    def _build_group_ids_cached(table, keys, gpu_compiler=None):
        """Cached wrapper: reuses group encoding when the same table object is queried.

        gpu_compiler is accepted for API compatibility but GPU group encoding via
        group_encode.mojo requires compare_exchange_weak which is not available in
        Mojo 26.1. Falls through to the CPU dictionary_encode path always.
        """
        cache_key = (id(table), table.num_rows, tuple(keys))
        cached = _GROUP_ENCODE_CACHE.get(cache_key)
        if cached is not None:
            return cached
        result = CustomOpsCompiler._build_group_ids(table, keys)
        _GROUP_ENCODE_CACHE[cache_key] = result
        return result

    def _build_group_ids_gpu_single_int(self, col_arr, key_name, n_rows):
        """GPU group encoding for a single integer key column via group_encode kernel.

        Returns (dense_ids, n_groups, unique_key_cols) matching _build_group_ids output,
        or None if the kernel call fails (falls back to CPU path).

        Hash table capacity = next power of two >= 4 * n_distinct_estimate.
        We conservatively use 2 * n_rows (over-estimates, wastes some VRAM, but always safe).
        """
        import math as _math
        try:
            keys_np = col_arr.to_numpy(zero_copy_only=False).astype(np.int32)
            n = len(keys_np)
            if n == 0:
                return np.array([], dtype=np.int32), 0, {key_name: pa.array([], type=pa.int32())}

            # Capacity: next power of two >= 2*n (load factor = 0.5)
            cap = 1
            while cap < 2 * n:
                cap *= 2

            capacity_np = np.array([cap], dtype=np.int32)
            key_table_np = np.full(cap, -2147483648, dtype=np.int32)  # INT32_MIN sentinel
            id_table_np = np.full(cap, -1, dtype=np.int32)

            cache_key = ("group_encode", n, cap, self._session_device)
            model = _POST_OP_MODEL_CACHE.get(cache_key)
            if model is None:
                k_type = TensorType(DType.int32, [n], self._device_ref)
                cap_type = TensorType(DType.int32, [1], self._device_ref)
                kt_type = TensorType(DType.int32, [cap], self._device_ref)
                graph = Graph(
                    name="mxframe_group_encode",
                    input_types=[k_type, cap_type, kt_type, kt_type],
                    custom_extensions=[Path(self.kernels_path)],
                )
                with graph:
                    gids_node, ng_node, _, _ = ops.custom(
                        name="group_encode",
                        values=[graph.inputs[0], graph.inputs[1],
                                graph.inputs[2], graph.inputs[3]],
                        out_types=[
                            TensorType(DType.int32, [n], self._device_ref),
                            TensorType(DType.int32, [1], self._device_ref),
                            TensorType(DType.int32, [cap], self._device_ref),
                            TensorType(DType.int32, [cap], self._device_ref),
                        ],
                        device=self._device_ref,
                    )
                    graph.output(gids_node, ng_node)
                model = self.session.load(graph)
                _POST_OP_MODEL_CACHE[cache_key] = model

            k_buf = driver.Buffer.from_numpy(keys_np).to(self._gpu_driver)
            c_buf = driver.Buffer.from_numpy(capacity_np).to(self._gpu_driver)
            kt_buf = driver.Buffer.from_numpy(key_table_np).to(self._gpu_driver)
            it_buf = driver.Buffer.from_numpy(id_table_np).to(self._gpu_driver)

            group_ids_t, n_groups_t = model.execute(k_buf, c_buf, kt_buf, it_buf)
            dense_ids = np.asarray(group_ids_t.to_numpy()).reshape(-1).astype(np.int32)
            n_groups = int(np.asarray(n_groups_t.to_numpy()).reshape(-1)[0])

            # Reconstruct unique key values: take the key value at each dense ID position.
            # Since IDs are assigned in first-encounter order by GPU threads, we find the
            # first index of each group ID to recover the original key value.
            first_occurrence = np.empty(n_groups, dtype=np.int64)
            seen = np.full(n_groups, False)
            for idx in range(n):
                gid = int(dense_ids[idx])
                if not seen[gid]:
                    first_occurrence[gid] = idx
                    seen[gid] = True

            unique_keys = col_arr.take(pa.array(first_occurrence))
            return dense_ids, n_groups, {key_name: unique_keys}

        except Exception:
            return None  # fall back to CPU path


