"""Abstract Syntax Tree (AST) for column-level operations in MXFrame."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_lazy_expr.ipynb.

# %% auto 0
__all__ = ['Expr', 'col', 'lit', 'when']

# %% ../nbs/01_lazy_expr.ipynb 2
from typing import Any, List, Optional, Union
from dataclasses import dataclass

# %% ../nbs/01_lazy_expr.ipynb 4
class Expr:
    """Base class for all lazy expressions."""
    def __init__(self, op: str, *args, **kwargs):
        self.op = op
        self.args = args
        self.kwargs = kwargs
        self._alias: Optional[str] = None

    def alias(self, name: str) -> 'Expr':
        """Rename the output of this expression."""
        self._alias = name
        return self

    def __add__(self, other: Union['Expr', Any]) -> 'Expr':
        return Expr("add", self, lit(other) if not isinstance(other, Expr) else other)

    def __sub__(self, other: Union['Expr', Any]) -> 'Expr':
        return Expr("sub", self, lit(other) if not isinstance(other, Expr) else other)

    def __mul__(self, other: Union['Expr', Any]) -> 'Expr':
        return Expr("mul", self, lit(other) if not isinstance(other, Expr) else other)

    def __truediv__(self, other: Union['Expr', Any]) -> 'Expr':
        return Expr("div", self, lit(other) if not isinstance(other, Expr) else other)

    def __eq__(self, other: Union['Expr', Any]) -> 'Expr': # type: ignore
        return Expr("eq", self, lit(other) if not isinstance(other, Expr) else other)

    def __gt__(self, other: Union['Expr', Any]) -> 'Expr':
        return Expr("gt", self, lit(other) if not isinstance(other, Expr) else other)

    def __lt__(self, other: Union['Expr', Any]) -> 'Expr':
        return Expr("lt", self, lit(other) if not isinstance(other, Expr) else other)

    def __ge__(self, other: Union['Expr', Any]) -> 'Expr':
        return Expr("ge", self, lit(other) if not isinstance(other, Expr) else other)

    def __le__(self, other: Union['Expr', Any]) -> 'Expr':
        return Expr("le", self, lit(other) if not isinstance(other, Expr) else other)

    def __and__(self, other: Union['Expr', Any]) -> 'Expr':
        return Expr("and", self, lit(other) if not isinstance(other, Expr) else other)

    def __or__(self, other: Union['Expr', Any]) -> 'Expr':
        return Expr("or", self, lit(other) if not isinstance(other, Expr) else other)

    def __ne__(self, other: Union['Expr', Any]) -> 'Expr':  # type: ignore
        return Expr("ne", self, lit(other) if not isinstance(other, Expr) else other)

    def __invert__(self) -> 'Expr':
        """Logical NOT — use as ~expr."""
        return Expr("not", self)

    def isin(self, values: list) -> 'Expr':
        """True for rows where this column's value is in *values*."""
        return Expr("isin", self, values)

    def startswith(self, prefix: str) -> 'Expr':
        """True for rows where this string column starts with *prefix*."""
        return Expr("startswith", self, prefix)

    def sum(self) -> 'Expr':
        return Expr("sum", self)

    def min(self) -> 'Expr':
        return Expr("min", self)

    def max(self) -> 'Expr':
        return Expr("max", self)

    def mean(self) -> 'Expr':
        return Expr("mean", self)

    def count(self) -> 'Expr':
        """Count the number of rows. After a filter, reflects filtered row count."""
        return Expr("count", self)

    def signature(self) -> tuple:
        """Return a hashable structural signature for graph caching."""
        def _sig(a):
            if isinstance(a, Expr): return a.signature()
            if isinstance(a, list): return ("list", tuple(a))
            return a
        child_sigs = tuple(_sig(a) for a in self.args)
        return (self.op, child_sigs)

    def __repr__(self) -> str:
        args_str = ", ".join(repr(a) for a in self.args)
        alias_str = f" AS {self._alias}" if self._alias else ""
        return f"{self.op}({args_str}){alias_str}"


# %% ../nbs/01_lazy_expr.ipynb 6
def col(name: str) -> Expr:
    """Create a column reference expression."""
    return Expr("col", name)

def lit(value: Any) -> Expr:
    """Create a literal value expression."""
    return Expr("lit", value)

def when(condition: 'Expr', then: Any, otherwise: Any = 0) -> 'Expr':
    """CASE WHEN condition THEN then ELSE otherwise END."""
    if not isinstance(then, Expr):      then      = lit(then)
    if not isinstance(otherwise, Expr): otherwise = lit(otherwise)
    return Expr("case_when", condition, then, otherwise)
