"""The relational algebra tree and the user-facing `LazyFrame` API."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_lazy_frame.ipynb.

# %% auto 0
__all__ = ['DeviceType', 'LogicalPlan', 'Scan', 'Filter', 'Project', 'Aggregate', 'Sort', 'Limit', 'Distinct', 'Join',
           'LazyFrame', 'LazyGroupBy', 'GPUFrame']

# %% ../nbs/02_lazy_frame.ipynb 2
from typing import Any, List, Literal, Optional, Union, Dict
from dataclasses import dataclass
from .lazy_expr import Expr, col
import pyarrow as pa


# %% ../nbs/02_lazy_frame.ipynb 4
class LogicalPlan:
    """Base class for all logical plan nodes."""
    def signature(self) -> tuple:
        """Return a hashable structural signature for graph caching."""
        raise NotImplementedError(f"signature() not implemented for {type(self).__name__}")

@dataclass
class Scan(LogicalPlan):
    """Represents reading data from a source (e.g., a PyArrow Table)."""
    table: pa.Table
    def signature(self) -> tuple:
        return ("Scan", tuple(self.table.column_names))

@dataclass
class Filter(LogicalPlan):
    """Represents filtering rows based on a predicate."""
    input: LogicalPlan
    predicate: Expr
    def signature(self) -> tuple:
        return ("Filter", self.input.signature(), self.predicate.signature())

@dataclass
class Project(LogicalPlan):
    """Represents selecting or computing columns."""
    input: LogicalPlan
    exprs: List[Expr]
    def signature(self) -> tuple:
        return ("Project", self.input.signature(), tuple(e.signature() for e in self.exprs))

@dataclass
class Aggregate(LogicalPlan):
    """Represents grouping and aggregating data."""
    input: LogicalPlan
    group_by: List[Expr]
    aggs: List[Expr]
    def signature(self) -> tuple:
        return ("Aggregate", self.input.signature(),
                tuple(e.signature() for e in self.group_by),
                tuple(e.signature() for e in self.aggs))

@dataclass
class Sort(LogicalPlan):
    """Represents sorting rows by one or more keys."""
    input: LogicalPlan
    by: List[Expr]
    descending: List[bool]
    def signature(self) -> tuple:
        return ("Sort", self.input.signature(),
                tuple(e.signature() for e in self.by),
                tuple(self.descending))

@dataclass
class Limit(LogicalPlan):
    """Represents taking only the first N rows."""
    input: LogicalPlan
    n: int
    def signature(self) -> tuple:
        return ("Limit", self.input.signature(), self.n)

@dataclass
class Distinct(LogicalPlan):
    """Represents removing duplicate rows (optionally on a subset of columns)."""
    input: LogicalPlan
    subset: Optional[List[str]] = None
    def signature(self) -> tuple:
        return ("Distinct", self.input.signature(),
                tuple(self.subset) if self.subset else ())


@dataclass
class Join(LogicalPlan):
    """Represents an inner join between two plan trees (first two-child node)."""
    left: LogicalPlan
    right: LogicalPlan
    left_on: List[str]
    right_on: List[str]
    how: str = "inner"
    def signature(self) -> tuple:
        return ("Join", self.left.signature(), self.right.signature(),
                tuple(self.left_on), tuple(self.right_on), self.how)


# %% ../nbs/02_lazy_frame.ipynb 6
DeviceType = Literal["cpu", "gpu", "auto"]


class LazyFrame:
    """A lazy DataFrame that builds a logical plan."""
    def __init__(self, plan):
        if isinstance(plan, pa.Table):
            plan = Scan(plan)
        self.plan = plan
        self._last_compile_provenance = None
        self._last_optimizer_trace = []

    def select(self, *exprs):
        """Select columns or compute new ones."""
        parsed_exprs = [col(e) if isinstance(e, str) else e for e in exprs]
        return LazyFrame(Project(self.plan, parsed_exprs))

    def filter(self, predicate):
        """Filter rows based on a condition."""
        return LazyFrame(Filter(self.plan, predicate))

    def groupby(self, *by):
        """Group data by one or more columns."""
        parsed_by = [col(b) if isinstance(b, str) else b for b in by]
        return LazyGroupBy(self, parsed_by)

    def compute(
        self,
        device: DeviceType = "auto",
        verbose: bool = False,
        optimize: bool = True,
        validate: bool = True,
    ) -> pa.Table:
        """Execute the logical plan and return the result.

        Args:
            device: "auto" (default), "cpu", or "gpu".
                "auto" — use GPU when available and N > AUTO_GPU_THRESHOLD rows, else CPU.
                "cpu"  — always run on CPU.
                "gpu"  — run on GPU; raises RuntimeError if no GPU is available.
            verbose: if True, print compile/execute timing and cache status.
            optimize: if True (default), run logical plan optimization passes first.
            validate: if True (default), validate logical plan invariants before execution.
        """
        from mxframe.custom_ops import CustomOpsCompiler
        plan = self.plan
        optimizer_trace = None

        if validate:
            from .plan_validation import validate_plan_or_raise
            validate_plan_or_raise(plan)

        if optimize:
            from .optimizer import optimize_plan
            opt = optimize_plan(self.plan)
            plan = opt.plan
            optimizer_trace = opt.trace
            if validate:
                from .plan_validation import validate_plan_or_raise
                validate_plan_or_raise(plan)
            if verbose and opt.trace:
                print("[mxframe] optimizer passes:")
                for line in opt.trace:
                    print(f"  - {line}")

        compiler = CustomOpsCompiler(device=device)
        result = compiler.compile_and_run(
            plan,
            verbose=verbose,
            optimizer_trace=optimizer_trace,
        )
        self._last_compile_provenance = dict(compiler.last_compile_provenance or {})
        self._last_optimizer_trace = list(optimizer_trace or [])
        return result

    def explain(
        self,
        optimized: bool = True,
        validate: bool = False,
        include_runtime: bool = False,
    ) -> str:
        """Return a readable plan explanation.

        Args:
            optimized: if True (default), include optimizer pass trace and optimized plan.
            validate: if True, include validation summaries for shown plans.
            include_runtime: if True, include last compile provenance from compute().
        """
        trace = []
        original_plan = self.plan
        plan = original_plan
        title = "LogicalPlan"
        if optimized:
            from .optimizer import optimize_plan
            opt = optimize_plan(self.plan)
            plan = opt.plan
            trace = opt.trace
            title = "OptimizedPlan"

        lines = [title, _format_plan(plan)]
        if validate:
            from .plan_validation import validate_plan
            shown_errors = validate_plan(plan)
            lines.append("Validation")
            lines.append("ok" if not shown_errors else f"errors={len(shown_errors)}")
            if optimized:
                orig_errors = validate_plan(original_plan)
                lines.append("OriginalValidation")
                lines.append("ok" if not orig_errors else f"errors={len(orig_errors)}")
        if optimized:
            lines.append("PassTrace")
            lines.extend(trace if trace else ["no-op"])
        if include_runtime:
            lines.append("LastCompileProvenance")
            if self._last_compile_provenance:
                for k, v in self._last_compile_provenance.items():
                    lines.append(f"{k}={v}")
            else:
                lines.append("none (run compute() first)")
        return "\n".join(lines)

    @property
    def last_compile_provenance(self) -> dict:
        """Return last compile/execute provenance captured during compute()."""
        return dict(self._last_compile_provenance or {})


    def sort(self, *by, descending=False):
        """Sort rows by one or more columns.

        Args:
            *by: Column names (str) or Expr objects to sort by.
            descending: bool or list of bool. If a single bool, applied to all keys.
        """
        parsed_by = [col(b) if isinstance(b, str) else b for b in by]
        if isinstance(descending, bool):
            desc_list = [descending] * len(parsed_by)
        else:
            desc_list = list(descending)
        return LazyFrame(Sort(self.plan, parsed_by, desc_list))

    def limit(self, n: int):
        """Take only the first N rows."""
        return LazyFrame(Limit(self.plan, n))

    def distinct(self, *subset):
        """Remove duplicate rows, optionally considering only a subset of columns.

        Args:
            *subset: Column names to consider for uniqueness.
                     If empty, all columns are used.
        """
        sub = list(subset) if subset else None
        return LazyFrame(Distinct(self.plan, sub))

    def to_gpu(self) -> 'GPUFrame':
        """Upload all numeric columns to GPU once and return a GPUFrame.

        The GPUFrame holds the device buffers in the module-level
        ``_GPU_BUFFER_CACHE`` so that every subsequent ``.compute()`` call
        on the same underlying data skips the PCIe transfer entirely.

        Raises ``RuntimeError`` if no GPU is available.
        """
        from .custom_ops import CustomOpsCompiler, _GPU_BUFFER_CACHE
        from max import driver
        import pyarrow as pa
        import numpy as np
        from pathlib import Path

        compiler_inst = CustomOpsCompiler(device="gpu")

        # Warm the GPU buffer cache by converting and uploading all numeric columns.
        table = self.plan.table if hasattr(self.plan, 'table') else None
        if table is None:
            raise ValueError("to_gpu() requires a LazyFrame built directly from a pa.Table (no prior transforms).")

        col_names = []
        gpu_bufs: Dict[str, Any] = {}
        for name in table.column_names:
            col = table.column(name)
            if isinstance(col, pa.ChunkedArray):
                col = col.combine_chunks()
            np_arr, _, _ = compiler_inst._column_to_numpy_cached(col)
            if np_arr is None:
                continue
            np_arr = compiler_inst._normalize_numeric_dtype(np_arr)
            if np_arr is None:
                continue
            col_names.append(name)
            gpu_buf, _ = compiler_inst._to_gpu_input(np_arr)
            gpu_bufs[name] = gpu_buf

        # Store under a stable key (no filter, no plan-specific signature)
        # so filter variations all reuse these buffers.
        stable_key = (id(table), table.num_rows, tuple(col_names), "gpu")
        _GPU_BUFFER_CACHE[stable_key] = gpu_bufs

        return GPUFrame(table, _compiler=compiler_inst)


    def join(self, other, *, on=None, left_on=None, right_on=None, how="inner"):
        """Inner join with another LazyFrame.

        Args:
            other: LazyFrame to join with.
            on: Column name(s) present in both frames (shorthand for left_on=right_on).
            left_on: Column name(s) in the left frame.
            right_on: Column name(s) in the right frame.
            how: Join type (currently only "inner" is supported).
        """
        if on is not None:
            if left_on is not None or right_on is not None:
                raise ValueError("Cannot specify both 'on' and 'left_on'/'right_on'")
            left_on = [on] if isinstance(on, str) else list(on)
            right_on = list(left_on)
        else:
            if left_on is None or right_on is None:
                raise ValueError("Must specify either 'on' or both 'left_on' and 'right_on'")
            left_on = [left_on] if isinstance(left_on, str) else list(left_on)
            right_on = [right_on] if isinstance(right_on, str) else list(right_on)
        return LazyFrame(Join(self.plan, other.plan, left_on, right_on, how))


class LazyGroupBy:
    """Intermediate object for grouping operations."""
    def __init__(self, df, by):
        self.df = df
        self.by = by

    def agg(self, *aggs) -> LazyFrame:
        """Compute aggregations for each group."""
        return LazyFrame(Aggregate(self.df.plan, self.by, list(aggs)))


def _format_plan(plan: LogicalPlan, indent: int = 0) -> str:
    """Pretty-print a logical plan tree."""
    pad = "  " * indent
    if isinstance(plan, Scan):
        return f"{pad}Scan(columns={list(plan.table.column_names)})"
    if isinstance(plan, Filter):
        head = f"{pad}Filter(predicate={plan.predicate.signature()})"
        return "\n".join([head, _format_plan(plan.input, indent + 1)])
    if isinstance(plan, Project):
        exprs = [e.signature() for e in plan.exprs]
        head = f"{pad}Project(exprs={exprs})"
        return "\n".join([head, _format_plan(plan.input, indent + 1)])
    if isinstance(plan, Aggregate):
        group_by = [e.signature() for e in plan.group_by]
        aggs = [e.signature() for e in plan.aggs]
        head = f"{pad}Aggregate(group_by={group_by}, aggs={aggs})"
        return "\n".join([head, _format_plan(plan.input, indent + 1)])
    if isinstance(plan, Sort):
        by = [e.signature() for e in plan.by]
        head = f"{pad}Sort(by={by}, descending={plan.descending})"
        return "\n".join([head, _format_plan(plan.input, indent + 1)])
    if isinstance(plan, Limit):
        head = f"{pad}Limit(n={plan.n})"
        return "\n".join([head, _format_plan(plan.input, indent + 1)])
    if isinstance(plan, Distinct):
        head = f"{pad}Distinct(subset={plan.subset})"
        return "\n".join([head, _format_plan(plan.input, indent + 1)])
    if isinstance(plan, Join):
        head = f"{pad}Join(how={plan.how}, left_on={plan.left_on}, right_on={plan.right_on})"
        left = _format_plan(plan.left, indent + 1)
        right = _format_plan(plan.right, indent + 1)
        return "\n".join([head, left, right])
    return f"{pad}{type(plan).__name__}"


class GPUFrame:
    """A GPU-resident DataFrame that holds column buffers on the device.

    Created via ``LazyFrame.to_gpu()`` — uploads all numeric columns once and
    keeps the device buffers alive across multiple ``.compute()`` calls.
    Subsequent queries on the same data skip the PCIe upload entirely because
    the ``_GPU_BUFFER_CACHE`` already contains the buffers.

    Usage::

        gdf = df.to_gpu()                          # upload once
        result1 = gdf.filter(col('a') > 5)\\
                      .groupby('dept').agg(col('salary').sum())\\
                      .compute()                   # no upload
        result2 = gdf.filter(col('a') > 10)\\
                      .groupby('dept').agg(col('salary').mean())\\
                      .compute()                   # still no upload

    The wrapped ``LazyFrame`` API (``filter``, ``select``, ``groupby``,
    ``sort``, ``limit``, ``distinct``, ``join``) is fully supported.
    Call ``.to_arrow()`` on any result to get a ``pa.Table``.
    """

    def __init__(self, table: pa.Table, _compiler=None):
        """Do not call directly — use ``LazyFrame.to_gpu()``."""
        self._table = table
        self._lf = LazyFrame(table)
        self._compiler = _compiler  # CustomOpsCompiler with warm session + pre-cached buffers

    # ── Lazy plan builders (delegate to wrapped LazyFrame) ──────────

    def filter(self, predicate) -> 'GPUFrame':
        return GPUFrame(self._table, self._compiler).__with_lf(self._lf.filter(predicate))

    def select(self, *exprs) -> 'GPUFrame':
        return GPUFrame(self._table, self._compiler).__with_lf(self._lf.select(*exprs))

    def sort(self, *by, descending=False) -> 'GPUFrame':
        return GPUFrame(self._table, self._compiler).__with_lf(self._lf.sort(*by, descending=descending))

    def limit(self, n: int) -> 'GPUFrame':
        return GPUFrame(self._table, self._compiler).__with_lf(self._lf.limit(n))

    def distinct(self, subset=None) -> 'GPUFrame':
        return GPUFrame(self._table, self._compiler).__with_lf(self._lf.distinct(subset))

    def groupby(self, *by) -> 'LazyGroupBy':
        return _GPUGroupBy(self, [col(b) if isinstance(b, str) else b for b in by])

    def __with_lf(self, lf: 'LazyFrame') -> 'GPUFrame':
        gf = GPUFrame(self._table, self._compiler)
        gf._lf = lf
        return gf

    # ── Execution ────────────────────────────────────────────────────

    def compute(self, verbose: bool = False, optimize: bool = True,
                validate: bool = True) -> pa.Table:
        """Execute the plan on GPU, reusing cached device buffers.

        Always runs on ``device='gpu'``; raises ``RuntimeError`` if no GPU
        is available.
        """
        return self._lf.compute(
            device="gpu",
            verbose=verbose,
            optimize=optimize,
            validate=validate,
        )

    def to_arrow(self) -> pa.Table:
        """Alias for ``compute()`` — explicit pull of result to CPU."""
        return self.compute()

    def __repr__(self) -> str:
        return (f"GPUFrame(rows={self._table.num_rows}, "
                f"cols={self._table.column_names})")


class _GPUGroupBy:
    """Intermediate groupby object for GPUFrame."""

    def __init__(self, gf: GPUFrame, by):
        self._gf = gf
        self._by = by

    def agg(self, *aggs) -> GPUFrame:
        lf_agg = LazyFrame(Aggregate(self._gf._lf.plan, self._by, list(aggs)))
        return self._gf.__class__(self._gf._table, self._gf._compiler).__with_lf_direct(lf_agg)

    def __with_lf_direct(self, lf) -> 'GPUFrame':
        gf = GPUFrame(self._gf._table, self._gf._compiler)
        gf._lf = lf
        return gf




