"""Abstract Syntax Tree (AST) for column-level operations in MXFrame."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_lazy_expr.ipynb.

# %% auto 0
__all__ = ['Expr', 'col', 'lit', 'when', 'row_number']

# %% ../nbs/01_lazy_expr.ipynb 2
from typing import Any, List, Optional, Union
from dataclasses import dataclass

# %% ../nbs/01_lazy_expr.ipynb 4
class Expr:
    """Base class for all lazy expressions."""
    def __init__(self, op: str, *args, **kwargs):
        self.op = op
        self.args = args
        self.kwargs = kwargs
        self._alias: Optional[str] = None

    def alias(self, name: str) -> 'Expr':
        """Rename the output of this expression."""
        self._alias = name
        return self

    def __add__(self, other: Union['Expr', Any]) -> 'Expr':
        return Expr("add", self, lit(other) if not isinstance(other, Expr) else other)

    def __sub__(self, other: Union['Expr', Any]) -> 'Expr':
        return Expr("sub", self, lit(other) if not isinstance(other, Expr) else other)

    def __mul__(self, other: Union['Expr', Any]) -> 'Expr':
        return Expr("mul", self, lit(other) if not isinstance(other, Expr) else other)

    def __truediv__(self, other: Union['Expr', Any]) -> 'Expr':
        return Expr("div", self, lit(other) if not isinstance(other, Expr) else other)

    def __eq__(self, other: Union['Expr', Any]) -> 'Expr': # type: ignore
        return Expr("eq", self, lit(other) if not isinstance(other, Expr) else other)

    def __gt__(self, other: Union['Expr', Any]) -> 'Expr':
        return Expr("gt", self, lit(other) if not isinstance(other, Expr) else other)

    def __lt__(self, other: Union['Expr', Any]) -> 'Expr':
        return Expr("lt", self, lit(other) if not isinstance(other, Expr) else other)

    def __ge__(self, other: Union['Expr', Any]) -> 'Expr':
        return Expr("ge", self, lit(other) if not isinstance(other, Expr) else other)

    def __le__(self, other: Union['Expr', Any]) -> 'Expr':
        return Expr("le", self, lit(other) if not isinstance(other, Expr) else other)

    def __and__(self, other: Union['Expr', Any]) -> 'Expr':
        return Expr("and", self, lit(other) if not isinstance(other, Expr) else other)

    def __or__(self, other: Union['Expr', Any]) -> 'Expr':
        return Expr("or", self, lit(other) if not isinstance(other, Expr) else other)

    def __ne__(self, other: Union['Expr', Any]) -> 'Expr':  # type: ignore
        return Expr("ne", self, lit(other) if not isinstance(other, Expr) else other)

    def __invert__(self) -> 'Expr':
        """Logical NOT — use as ~expr."""
        return Expr("not", self)

    def isin(self, values: list) -> 'Expr':
        """True for rows where this column's value is in *values*."""
        return Expr("isin", self, values)

    def startswith(self, prefix: str) -> 'Expr':
        """True for rows where this string column starts with *prefix*."""
        return Expr("startswith", self, prefix)

    def contains(self, pattern: str) -> 'Expr':
        """True for rows where this string column contains *pattern* (substring match)."""
        return Expr("contains", self, pattern)

    def between(self, lo, hi) -> 'Expr':
        """True for rows where lo <= value <= hi (inclusive on both ends)."""
        lo_expr = lit(lo) if not isinstance(lo, Expr) else lo
        hi_expr = lit(hi) if not isinstance(hi, Expr) else hi
        return Expr("and", Expr("ge", self, lo_expr), Expr("le", self, hi_expr))

    # ── Window / analytic functions ──────────────────────────────────────────

    def over(self, *partition_by, order_by=None, descending: bool = False) -> 'Expr':
        """Evaluate this window/agg expr within each partition, broadcasting values
        back to every row in the partition.

        Usage::

            col("amount").sum().over("region")              # group sum per row
            col("score").rank().over("region", order_by="score")
            col("val").lag(1).over("grp", order_by="date")
        """
        order_cols = [order_by] if isinstance(order_by, str) else list(order_by or [])
        spec = (list(partition_by), order_cols, descending)
        return Expr("window", self, spec)

    def rank(self) -> 'Expr':
        """Rank in ascending order (ties share same rank, gaps follow: 1,2,2,4…)."""
        return Expr("rank", self)

    def dense_rank(self) -> 'Expr':
        """Dense rank — ties share rank with no gaps (1,2,2,3…)."""
        return Expr("dense_rank", self)

    def lag(self, n: int = 1, default=None) -> 'Expr':
        """Value from N rows earlier in the current ordering context."""
        return Expr("lag", self, n, default)

    def lead(self, n: int = 1, default=None) -> 'Expr':
        """Value from N rows later in the current ordering context."""
        return Expr("lead", self, n, default)

    def cum_sum(self) -> 'Expr':
        """Running cumulative sum (from first row to current row in context)."""
        return Expr("cum_sum", self)

    def year(self) -> 'Expr':
        """Extract the year from an integer YYYYMMDD date column (or Arrow date32)."""
        return Expr("year", self)

    def sum(self) -> 'Expr':
        return Expr("sum", self)

    def min(self) -> 'Expr':
        return Expr("min", self)

    def max(self) -> 'Expr':
        return Expr("max", self)

    def mean(self) -> 'Expr':
        return Expr("mean", self)

    def count(self) -> 'Expr':
        """Count the number of rows. After a filter, reflects filtered row count."""
        return Expr("count", self)

    def signature(self) -> tuple:
        """Return a hashable structural signature for graph caching."""
        def _sig(a):
            if isinstance(a, Expr): return a.signature()
            if isinstance(a, list): return ("list", tuple(a))
            return a
        child_sigs = tuple(_sig(a) for a in self.args)
        return (self.op, child_sigs)

    def __repr__(self) -> str:
        args_str = ", ".join(repr(a) for a in self.args)
        alias_str = f" AS {self._alias}" if self._alias else ""
        return f"{self.op}({args_str}){alias_str}"


# %% ../nbs/01_lazy_expr.ipynb 6
def col(name: str) -> Expr:
    """Create a column reference expression."""
    return Expr("col", name)

def lit(value: Any) -> Expr:
    """Create a literal value expression."""
    return Expr("lit", value)

def when(condition: 'Expr', then: Any, otherwise: Any = 0) -> 'Expr':
    """CASE WHEN condition THEN then ELSE otherwise END."""
    if not isinstance(then, Expr):      then      = lit(then)
    if not isinstance(otherwise, Expr): otherwise = lit(otherwise)
    return Expr("case_when", condition, then, otherwise)

def row_number() -> 'Expr':
    """Create a row-number expression (1-based, no input column needed).

    Use with ``.over()`` to get row numbers within a partition::

        row_number().over("region", order_by="date").alias("rn")

    Without ``.over()``, numbers the whole table sequentially.
    """
    return Expr("row_number")
