"""Column operations for MXFrame - arithmetic, comparisons, aggregations."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_ops.ipynb.

# %% auto 0
__all__ = ['Scalar', 'MXColumn', 'filter_frame', 'assign_columns', 'col']

# %% ../nbs/01_ops.ipynb 4
import pyarrow as pa
import pyarrow.compute as pc  # Only for filter/take operations
import numpy as np
from typing import Union, List, Optional, Any, Literal
from .core import MXFrame
from mxframe.max_ops import (
    DeviceType,
    max_sum, max_mean, max_min, max_max, max_count, max_std,
)

# Element-wise ops not yet implemented - use PyArrow fallback
def _pa_fallback_binop(op_name, a, b):
    """Fallback to PyArrow compute for element-wise ops."""
    import pyarrow.compute as pc
    op = getattr(pc, op_name)
    return op(a, b)

# %% ../nbs/01_ops.ipynb 5
Scalar = Union[int, float, bool]

# %% ../nbs/01_ops.ipynb 6
class MXColumn:
    """
    Wrapper around PyArrow ChunkedArray with arithmetic and comparison operators.
    
    Uses MAX Engine for ALL compute (CPU or GPU), PyArrow only for storage.
    
    Example:
        >>> col = MXColumn(pa.chunked_array([[1, 2, 3]]))
        >>> result = col * 2 + 1
        >>> mask = col > 1
        >>> total = col.sum(device="gpu")  # Use GPU for aggregation
    """
    
    def __init__(self, data: Union[pa.ChunkedArray, pa.Array, list, np.ndarray], 
                 name: str = "", device: DeviceType = "cpu"):
        if isinstance(data, pa.ChunkedArray):
            self._data = data
        elif isinstance(data, pa.Array):
            self._data = pa.chunked_array([data])
        elif isinstance(data, (list, np.ndarray)):
            self._data = pa.chunked_array([pa.array(data)])
        else:
            raise TypeError(f"Cannot create MXColumn from {type(data)}")
        self._name = name
        self._device = device
    
    @property
    def name(self) -> str:
        return self._name
    
    @property
    def dtype(self) -> pa.DataType:
        return self._data.type
    
    @property
    def device(self) -> DeviceType:
        return self._device
    
    def __len__(self) -> int:
        return len(self._data)
    
    def to_arrow(self) -> pa.ChunkedArray:
        return self._data
    
    def to_numpy(self) -> np.ndarray:
        return self._data.to_numpy(zero_copy_only=False)
    
    def to_pylist(self) -> list:
        return self._data.to_pylist()
    
    def to(self, device: DeviceType) -> 'MXColumn':
        """Return column targeting a different device."""
        return MXColumn(self._data, self._name, device)
    
    def _other_numpy(self, other: Union['MXColumn', Scalar]) -> np.ndarray:
        """Convert other operand to numpy array."""
        if isinstance(other, MXColumn):
            return other.to_numpy()
        else:
            return other  # Scalar - PyArrow compute handles it
    
    # ==================== Arithmetic (PyArrow fallback) ====================
    
    def __add__(self, other: Union['MXColumn', Scalar]) -> 'MXColumn':
        other_data = other._data if isinstance(other, MXColumn) else other
        result = pc.add(self._data, other_data)
        return MXColumn(result, device=self._device)
    
    def __radd__(self, other: Scalar) -> 'MXColumn':
        result = pc.add(self._data, other)
        return MXColumn(result, device=self._device)
    
    def __sub__(self, other: Union['MXColumn', Scalar]) -> 'MXColumn':
        other_data = other._data if isinstance(other, MXColumn) else other
        result = pc.subtract(self._data, other_data)
        return MXColumn(result, device=self._device)
    
    def __rsub__(self, other: Scalar) -> 'MXColumn':
        result = pc.subtract(other, self._data)
        return MXColumn(result, device=self._device)
    
    def __mul__(self, other: Union['MXColumn', Scalar]) -> 'MXColumn':
        other_data = other._data if isinstance(other, MXColumn) else other
        result = pc.multiply(self._data, other_data)
        return MXColumn(result, device=self._device)
    
    def __rmul__(self, other: Scalar) -> 'MXColumn':
        result = pc.multiply(self._data, other)
        return MXColumn(result, device=self._device)
    
    def __truediv__(self, other: Union['MXColumn', Scalar]) -> 'MXColumn':
        other_data = other._data if isinstance(other, MXColumn) else other
        result = pc.divide(self._data, other_data)
        return MXColumn(result, device=self._device)
    
    def __rtruediv__(self, other: Scalar) -> 'MXColumn':
        result = pc.divide(other, self._data)
        return MXColumn(result, device=self._device)
    
    def __neg__(self) -> 'MXColumn':
        result = pc.negate(self._data)
        return MXColumn(result, device=self._device)
    
    # ==================== Comparisons (PyArrow fallback) ====================
    
    def __gt__(self, other: Union['MXColumn', Scalar]) -> 'MXColumn':
        other_data = other._data if isinstance(other, MXColumn) else other
        result = pc.greater(self._data, other_data)
        return MXColumn(result, device=self._device)
    
    def __ge__(self, other: Union['MXColumn', Scalar]) -> 'MXColumn':
        other_data = other._data if isinstance(other, MXColumn) else other
        result = pc.greater_equal(self._data, other_data)
        return MXColumn(result, device=self._device)
    
    def __lt__(self, other: Union['MXColumn', Scalar]) -> 'MXColumn':
        other_data = other._data if isinstance(other, MXColumn) else other
        result = pc.less(self._data, other_data)
        return MXColumn(result, device=self._device)
    
    def __le__(self, other: Union['MXColumn', Scalar]) -> 'MXColumn':
        other_data = other._data if isinstance(other, MXColumn) else other
        result = pc.less_equal(self._data, other_data)
        return MXColumn(result, device=self._device)
    
    def __eq__(self, other: Union['MXColumn', Scalar]) -> 'MXColumn':
        other_data = other._data if isinstance(other, MXColumn) else other
        result = pc.equal(self._data, other_data)
        return MXColumn(result, device=self._device)
    
    def __ne__(self, other: Union['MXColumn', Scalar]) -> 'MXColumn':
        other_data = other._data if isinstance(other, MXColumn) else other
        result = pc.not_equal(self._data, other_data)
        return MXColumn(result, device=self._device)
    
    # ==================== Boolean Ops (PyArrow fallback) ====================
    
    def __and__(self, other: 'MXColumn') -> 'MXColumn':
        result = pc.and_(self._data, other._data)
        return MXColumn(result, device=self._device)
    
    def __or__(self, other: 'MXColumn') -> 'MXColumn':
        result = pc.or_(self._data, other._data)
        return MXColumn(result, device=self._device)
    
    def __invert__(self) -> 'MXColumn':
        result = pc.invert(self._data)
        return MXColumn(result, device=self._device)
    
    # ==================== Aggregations (MAX Engine) ====================
    
    def sum(self, device: DeviceType = None) -> Scalar:
        """Sum all values using MAX Engine."""
        dev = device or self._device
        return max_sum(self.to_numpy(), device=dev)
    
    def mean(self, device: DeviceType = None) -> float:
        """Mean of all values using MAX Engine."""
        dev = device or self._device
        return max_mean(self.to_numpy(), device=dev)
    
    def min(self, device: DeviceType = None) -> Scalar:
        """Minimum value using MAX Engine."""
        dev = device or self._device
        return max_min(self.to_numpy(), device=dev)
    
    def max(self, device: DeviceType = None) -> Scalar:
        """Maximum value using MAX Engine."""
        dev = device or self._device
        return max_max(self.to_numpy(), device=dev)
    
    def count(self, device: DeviceType = None) -> int:
        """Count elements using MAX Engine."""
        dev = device or self._device
        return max_count(self.to_numpy(), device=dev)
    
    def std(self, device: DeviceType = None) -> float:
        """Standard deviation using MAX Engine."""
        dev = device or self._device
        return max_std(self.to_numpy(), device=dev)
    
    # ==================== Display ====================
    
    def __repr__(self) -> str:
        name_str = f"'{self._name}'" if self._name else ""
        return f"MXColumn{name_str}({len(self)}, {self.dtype}, device={self._device})"
    
    def __str__(self) -> str:
        return str(self._data)

# %% ../nbs/01_ops.ipynb 10
def filter_frame(frame: MXFrame, mask: Union[MXColumn, pa.ChunkedArray]) -> MXFrame:
    """
    Filter MXFrame rows by boolean mask.
    
    Args:
        frame: MXFrame to filter
        mask: Boolean mask (MXColumn or ChunkedArray)
        
    Returns:
        New MXFrame with filtered rows
    """
    mask_data = mask._data if isinstance(mask, MXColumn) else mask
    filtered_table = pc.filter(frame.to_arrow(), mask_data)
    return MXFrame(filtered_table)

# %% ../nbs/01_ops.ipynb 11
def assign_columns(frame: MXFrame, **kwargs) -> MXFrame:
    """
    Create new MXFrame with additional/replaced columns.
    
    Args:
        frame: Source MXFrame
        **kwargs: Column name -> MXColumn or array-like
        
    Returns:
        New MXFrame with added columns
        
    Example:
        >>> new_frame = assign_columns(frame, 
        ...     disc_price=frame['price'] * (1 - frame['disc']))
    """
    table = frame.to_arrow()
    
    for name, col in kwargs.items():
        if isinstance(col, MXColumn):
            arr = col.to_arrow()
        elif isinstance(col, pa.ChunkedArray):
            arr = col
        elif isinstance(col, (list, np.ndarray)):
            arr = pa.chunked_array([pa.array(col)])
        else:
            raise TypeError(f"Cannot assign column from {type(col)}")
        
        # Check if column exists, replace or append
        if name in table.column_names:
            idx = table.column_names.index(name)
            table = table.set_column(idx, name, arr)
        else:
            table = table.append_column(name, arr)
    
    return MXFrame(table)

# %% ../nbs/01_ops.ipynb 12
def col(frame: MXFrame, name: str) -> MXColumn:
    """Get column from MXFrame as MXColumn."""
    return MXColumn(frame.to_arrow().column(name), name=name)
