"""Zero-copy connection between PyArrow and MAX Engine."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_core_bridge.ipynb.

# %% auto 0
__all__ = ['ARROW_TO_MAX_DTYPE', 'ARROW_TO_NUMPY_DTYPE', 'DeviceType', 'get_max_dtype', 'get_numpy_dtype', 'arrow_to_numpy_view',
           'arrow_to_max_tensor', 'MXFrame']

# %% ../nbs/01_core_bridge.ipynb 2
import pyarrow as pa
import numpy as np
from typing import Dict, Optional, Union, Literal
from max import driver
from max.dtype import DType

# %% ../nbs/01_core_bridge.ipynb 4
ARROW_TO_MAX_DTYPE: Dict[pa.DataType, DType] = {
    pa.int8(): DType.int8,
    pa.int16(): DType.int16,
    pa.int32(): DType.int32,
    pa.int64(): DType.int64,
    pa.uint8(): DType.uint8,
    pa.uint16(): DType.uint16,
    pa.uint32(): DType.uint32,
    pa.uint64(): DType.uint64,
    pa.float32(): DType.float32,
    pa.float64(): DType.float64,
    pa.date32(): DType.int32,
}

ARROW_TO_NUMPY_DTYPE: Dict[pa.DataType, np.dtype] = {
    pa.int8(): np.dtype('int8'),
    pa.int16(): np.dtype('int16'),
    pa.int32(): np.dtype('int32'),
    pa.int64(): np.dtype('int64'),
    pa.uint8(): np.dtype('uint8'),
    pa.uint16(): np.dtype('uint16'),
    pa.uint32(): np.dtype('uint32'),
    pa.uint64(): np.dtype('uint64'),
    pa.float32(): np.dtype('float32'),
    pa.float64(): np.dtype('float64'),
    pa.date32(): np.dtype('int32'),
}

def get_max_dtype(arrow_type: pa.DataType) -> DType:
    """Get MAX DType for an Arrow type."""
    if arrow_type in ARROW_TO_MAX_DTYPE:
        return ARROW_TO_MAX_DTYPE[arrow_type]
    raise TypeError(f"Unsupported Arrow type: {arrow_type}")


def get_numpy_dtype(arrow_type: pa.DataType) -> np.dtype:
    """Get NumPy dtype for an Arrow type."""
    if arrow_type in ARROW_TO_NUMPY_DTYPE:
        return ARROW_TO_NUMPY_DTYPE[arrow_type]
    raise TypeError(f"Unsupported Arrow type: {arrow_type}")

# %% ../nbs/01_core_bridge.ipynb 6
def arrow_to_numpy_view(arr: Union[pa.Array, pa.ChunkedArray]) -> np.ndarray:
    """
    Get a zero-copy NumPy view of an Arrow array.
    
    Args:
        arr: PyArrow Array or ChunkedArray (primitive type, no nulls)
        
    Returns:
        NumPy ndarray viewing the same memory
        
    Raises:
        ValueError: If array has nulls or isn't contiguous
        TypeError: If type isn't supported for zero-copy
    """
    # Handle ChunkedArray - combine if needed
    if isinstance(arr, pa.ChunkedArray):
        if arr.num_chunks == 1:
            arr = arr.chunk(0)
        else:
            # Multiple chunks - must combine (may copy)
            arr = arr.combine_chunks()
    
    # Check for nulls
    if arr.null_count > 0:
        raise ValueError(f"Array has {arr.null_count} nulls - zero-copy not possible")
    
    # Try direct zero-copy
    try:
        return arr.to_numpy(zero_copy_only=True)
    except pa.ArrowInvalid:
        # Special handling for Date32 - reinterpret buffer as int32
        if pa.types.is_date32(arr.type):
            data_buffer = arr.buffers()[1]
            return np.frombuffer(data_buffer, dtype=np.int32)
        raise TypeError(f"Cannot create zero-copy view for {arr.type}")

# %% ../nbs/01_core_bridge.ipynb 7
def arrow_to_max_tensor(
    arr: Union[pa.Array, pa.ChunkedArray],
    device: Optional[driver.Device] = None
) -> driver.Tensor:
    """
    Zero-copy bridge from PyArrow array to MAX Tensor.
    
    Path: Arrow → NumPy view → MAX Tensor
    
    On CPU: True zero-copy (same memory) via from_numpy
    On GPU: Copies to device memory (unavoidable)
    
    Args:
        arr: PyArrow Array or ChunkedArray
        device: Target device (None = CPU)
        
    Returns:
        MAX Tensor ready for graph execution
        
    Example:
        >>> arr = pa.array([1.0, 2.0, 3.0])
        >>> tensor = arrow_to_max_tensor(arr)
        >>> # tensor shares memory with arr on CPU
    """
    # Get zero-copy NumPy view
    np_view = arrow_to_numpy_view(arr)
    
    # Create MAX Tensor from NumPy (zero-copy for contiguous arrays)
    tensor = driver.Tensor.from_numpy(np_view)
    
    # Copy to GPU if requested
    if device is not None and not device.is_host:
        return tensor.to(device)
    
    return tensor

# %% ../nbs/01_core_bridge.ipynb 9
DeviceType = Literal["cpu", "gpu", "auto"]

class MXFrame:
    """
    PyArrow-backed DataFrame with zero-copy MAX Engine integration.
    
    Stores data in PyArrow format and provides zero-copy access
    to MAX tensors for GPU/CPU compute.
    
    Example:
        >>> df = MXFrame({'price': [10.0, 20.0], 'qty': [1, 2]})
        >>> tensor = df.to_max_tensor('price')
        >>> # tensor shares memory with underlying Arrow buffer
    """
    
    def __init__(self, data: Union[pa.Table, Dict[str, list]]):
        """
        Create MXFrame from Arrow Table or dict of lists.
        
        Args:
            data: PyArrow Table or dict of column_name -> values
        """
        if isinstance(data, pa.Table):
            self._table = data
        elif isinstance(data, dict):
            self._table = pa.table(data)
        else:
            raise TypeError(f"Expected Table or dict, got {type(data)}")
        
        # Cache for numpy views (keeps references alive)
        self._numpy_cache: Dict[str, np.ndarray] = {}
        
        # Resolved device
        self._device: Optional[driver.Device] = None
    
    @property
    def columns(self) -> list:
        """Column names."""
        return self._table.column_names
    
    @property
    def num_rows(self) -> int:
        """Number of rows."""
        return self._table.num_rows
    
    @property
    def num_columns(self) -> int:
        """Number of columns."""
        return self._table.num_columns
    
    def __len__(self) -> int:
        return self.num_rows
    
    def __repr__(self) -> str:
        return f"MXFrame({self.num_rows} rows, {self.columns})"
    
    def column(self, name: str) -> pa.ChunkedArray:
        """Get Arrow column by name."""
        return self._table.column(name)
    
    def __getitem__(self, name: str) -> pa.ChunkedArray:
        """Get Arrow column by name."""
        return self.column(name)
    
    def to_arrow(self) -> pa.Table:
        """Get underlying Arrow table."""
        return self._table
    
    # ========== Zero-Copy Bridge Methods ==========
    
    def to_numpy(self, column: str) -> np.ndarray:
        """
        Get zero-copy NumPy view of column.
        
        Caches the view to keep memory reference alive.
        """
        if column not in self._numpy_cache:
            self._numpy_cache[column] = arrow_to_numpy_view(self._table.column(column))
        return self._numpy_cache[column]
    
    def to_max_tensor(self, column: str, device: Optional[driver.Device] = None) -> driver.Tensor:
        """
        Get zero-copy MAX Tensor for column.
        
        Args:
            column: Column name
            device: Target device (None = CPU)
            
        Returns:
            MAX Tensor (zero-copy on CPU)
        """
        return arrow_to_max_tensor(self._table.column(column), device)
    
    def get_buffer_address(self, column: str) -> int:
        """
        Get memory address of column's data buffer.
        
        Useful for verifying zero-copy.
        """
        arr = self._table.column(column)
        if isinstance(arr, pa.ChunkedArray):
            arr = arr.chunk(0) if arr.num_chunks == 1 else arr.combine_chunks()
        return arr.buffers()[1].address
