"""The relational algebra tree and the user-facing `LazyFrame` API."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_lazy_frame.ipynb.

# %% auto 0
__all__ = ['DeviceType', 'LogicalPlan', 'Scan', 'Filter', 'Project', 'Aggregate', 'LazyFrame', 'LazyGroupBy']

# %% ../nbs/02_lazy_frame.ipynb 2
from typing import Any, List, Literal, Optional, Union, Dict
from dataclasses import dataclass
from .lazy_expr import Expr, col
import pyarrow as pa


# %% ../nbs/02_lazy_frame.ipynb 4
class LogicalPlan:
    """Base class for all logical plan nodes."""
    pass

@dataclass
class Scan(LogicalPlan):
    """Represents reading data from a source (e.g., a PyArrow Table)."""
    table: pa.Table

@dataclass
class Filter(LogicalPlan):
    """Represents filtering rows based on a predicate."""
    input: LogicalPlan
    predicate: Expr

@dataclass
class Project(LogicalPlan):
    """Represents selecting or computing columns."""
    input: LogicalPlan
    exprs: List[Expr]

@dataclass
class Aggregate(LogicalPlan):
    """Represents grouping and aggregating data."""
    input: LogicalPlan
    group_by: List[Expr]
    aggs: List[Expr]

# %% ../nbs/02_lazy_frame.ipynb 6
# Device type used by compute()
DeviceType = Literal["cpu", "gpu", "auto"]


class LazyFrame:
    """A lazy DataFrame that builds a logical plan."""
    def __init__(self, plan):
        self.plan = plan

    def select(self, *exprs):
        """Select columns or compute new ones."""
        parsed_exprs = [col(e) if isinstance(e, str) else e for e in exprs]
        return LazyFrame(Project(self.plan, parsed_exprs))

    def filter(self, predicate):
        """Filter rows based on a condition."""
        return LazyFrame(Filter(self.plan, predicate))

    def groupby(self, *by):
        """Group data by one or more columns."""
        parsed_by = [col(b) if isinstance(b, str) else b for b in by]
        return LazyGroupBy(self, parsed_by)

    def compute(self, device: DeviceType = "cpu") -> pa.Table:
        """Execute the logical plan and return the result.

        Args:
            device: "cpu" (default), "gpu", or "auto".
                "cpu"  — always run on CPU.
                "gpu"  — run on GPU; raises RuntimeError if no GPU is available.
                "auto" — use GPU when available and N > 100K rows, else CPU.
        """
        from mxframe.custom_ops import CustomOpsCompiler
        return CustomOpsCompiler(device=device).compile_and_run(self.plan)


class LazyGroupBy:
    """Intermediate object for grouping operations."""
    def __init__(self, df, by):
        self.df = df
        self.by = by

    def agg(self, *aggs) -> LazyFrame:
        """Compute aggregations for each group."""
        return LazyFrame(Aggregate(self.df.plan, self.by, list(aggs)))

